import type { Story, AIAnalysis } from "@/types";

export const MOCK_STORIES: Story[] = [
  {
    id: "story-001",
    title: "Federal Reserve Holds Interest Rates Steady Amid Economic Uncertainty",
    summary:
      "The Federal Reserve announced it would maintain current interest rates, citing mixed economic signals including persistent inflation and a cooling job market.",
    category: "business",
    imageUrl:
      "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    publishedRange: { from: "2024-11-15T10:00:00Z", to: "2024-11-15T18:30:00Z" },
    sources: [
      {
        id: "src-001-1",
        outlet: "Reuters",
        outletDomain: "reuters.com",
        headline: "Fed holds rates, signals cautious path ahead",
        snippet: "The Federal Reserve kept its benchmark interest rate unchanged Wednesday, with Chair Jerome Powell emphasizing that policymakers need more data before considering cuts.",
        url: "https://reuters.com",
        publishedAt: "2024-11-15T10:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-001-2",
        outlet: "Fox Business",
        outletDomain: "foxbusiness.com",
        headline: "Fed freezes rates again — inflation fight not over, Powell warns",
        snippet: "The Federal Reserve once again refused to cut interest rates, with Jerome Powell warning that inflation remains too high and the central bank will not rush to ease policy.",
        url: "https://foxbusiness.com",
        publishedAt: "2024-11-15T11:15:00Z",
        tone: "critical",
      },
      {
        id: "src-001-3",
        outlet: "Bloomberg",
        outletDomain: "bloomberg.com",
        headline: "Fed pauses rate cycle, markets rally on dovish commentary",
        snippet: "Federal Reserve officials voted unanimously to hold rates steady, while market participants focused on hints of future easing embedded in the post-meeting statement.",
        url: "https://bloomberg.com",
        publishedAt: "2024-11-15T12:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-001-4",
        outlet: "NPR",
        outletDomain: "npr.org",
        headline: "What the Fed's rate decision means for everyday Americans",
        snippet: "The Federal Reserve held interest rates steady for the third consecutive meeting, a decision that will keep borrowing costs elevated for mortgages, car loans, and credit cards.",
        url: "https://npr.org",
        publishedAt: "2024-11-15T14:00:00Z",
        tone: "neutral",
      },
    ],
    tags: ["federal reserve", "interest rates", "economy", "inflation"],
  },
  {
    id: "story-002",
    title: "Major AI Lab Releases Multimodal Model Claiming Human-Level Reasoning",
    summary:
      "A leading artificial intelligence company unveiled a new model it claims surpasses human performance on several benchmark reasoning tasks, reigniting debates about AGI timelines.",
    category: "technology",
    imageUrl:
      "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80",
    publishedRange: { from: "2024-11-14T09:00:00Z", to: "2024-11-14T22:00:00Z" },
    sources: [
      {
        id: "src-002-1",
        outlet: "The Verge",
        outletDomain: "theverge.com",
        headline: "New AI model claims human-level reasoning — researchers are skeptical",
        snippet: "The company's announcement was met with excitement from investors and skepticism from independent AI researchers who questioned the methodology behind the benchmark scores.",
        url: "https://theverge.com",
        publishedAt: "2024-11-14T09:00:00Z",
        tone: "mixed",
      },
      {
        id: "src-002-2",
        outlet: "Wired",
        outletDomain: "wired.com",
        headline: "The AI reasoning revolution is here — or is it?",
        snippet: "Wired examines what human-level reasoning actually means and why benchmark performance may not translate to real-world intelligence.",
        url: "https://wired.com",
        publishedAt: "2024-11-14T11:30:00Z",
        tone: "critical",
      },
      {
        id: "src-002-3",
        outlet: "TechCrunch",
        outletDomain: "techcrunch.com",
        headline: "AI startup raises $2B on the back of breakthrough reasoning model",
        snippet: "The announcement coincided with a massive funding round, raising questions about whether the timing was driven by scientific progress or investor relations.",
        url: "https://techcrunch.com",
        publishedAt: "2024-11-14T15:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-002-4",
        outlet: "BBC Technology",
        outletDomain: "bbc.com",
        headline: "AI that thinks like humans: what does it really mean?",
        snippet: "The BBC explores the philosophical and practical implications of a machine that can reportedly reason at or above the level of a typical adult human.",
        url: "https://bbc.com",
        publishedAt: "2024-11-14T18:00:00Z",
        tone: "neutral",
      },
    ],
    tags: ["artificial intelligence", "AI", "machine learning", "AGI"],
  },
  {
    id: "story-003",
    title: "Climate Summit Ends with Landmark Fossil Fuel Agreement",
    summary:
      "Delegates from 190 countries reached a historic accord committing to phase out fossil fuels over the next two decades, though critics argue the timeline is insufficient.",
    category: "world",
    imageUrl:
      "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&q=80",
    publishedRange: { from: "2024-11-13T08:00:00Z", to: "2024-11-13T20:00:00Z" },
    sources: [
      {
        id: "src-003-1",
        outlet: "The Guardian",
        outletDomain: "theguardian.com",
        headline: "Climate deal 'too little, too late' say scientists as summit wraps",
        snippet: "Environmental scientists and activist groups expressed disappointment with the 20-year phase-out timeline, arguing it falls far short of what is needed to limit warming to 1.5°C.",
        url: "https://theguardian.com",
        publishedAt: "2024-11-13T10:00:00Z",
        tone: "critical",
      },
      {
        id: "src-003-2",
        outlet: "Associated Press",
        outletDomain: "apnews.com",
        headline: "Nations agree to phase out fossil fuels in historic UN climate deal",
        snippet: "In a breakthrough moment at the COP climate conference, world leaders committed to a binding timeline to transition away from coal, oil, and gas over the next two decades.",
        url: "https://apnews.com",
        publishedAt: "2024-11-13T12:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-003-3",
        outlet: "Wall Street Journal",
        outletDomain: "wsj.com",
        headline: "Climate pact threatens energy security, industry groups warn",
        snippet: "Business and energy industry organizations cautioned that a rushed fossil fuel phase-out could trigger supply disruptions and economic instability in energy-dependent nations.",
        url: "https://wsj.com",
        publishedAt: "2024-11-13T14:30:00Z",
        tone: "critical",
      },
      {
        id: "src-003-4",
        outlet: "CNN",
        outletDomain: "cnn.com",
        headline: "World leaders hail 'historic' fossil fuel deal at climate summit",
        snippet: "World leaders from the US, EU, and major emerging economies praised the agreement, calling it the most significant climate commitment since the Paris Accord.",
        url: "https://cnn.com",
        publishedAt: "2024-11-13T16:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["climate change", "COP", "fossil fuels", "environment"],
  },
  {
    id: "story-004",
    title: "Senate Passes Sweeping Immigration Reform Bill",
    summary:
      "The Senate approved a bipartisan immigration reform package that includes a path to citizenship for undocumented immigrants and increased border security funding.",
    category: "politics",
    imageUrl:
      "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&q=80",
    publishedRange: { from: "2024-11-12T14:00:00Z", to: "2024-11-12T23:00:00Z" },
    sources: [
      {
        id: "src-004-1",
        outlet: "CNN Politics",
        outletDomain: "cnn.com",
        headline: "Senate passes landmark immigration bill in rare bipartisan vote",
        snippet: "The legislation, which passed 64-36, represents the most significant overhaul of U.S. immigration law in nearly four decades.",
        url: "https://cnn.com",
        publishedAt: "2024-11-12T14:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-004-2",
        outlet: "Fox News",
        outletDomain: "foxnews.com",
        headline: "Senate immigration bill slammed as 'amnesty' by conservatives",
        snippet: "Critics on the right blasted the Senate-passed immigration legislation as a massive expansion of legal status for illegal aliens that will incentivize more border crossings.",
        url: "https://foxnews.com",
        publishedAt: "2024-11-12T15:30:00Z",
        tone: "critical",
      },
      {
        id: "src-004-3",
        outlet: "New York Times",
        outletDomain: "nytimes.com",
        headline: "What's in the Senate immigration bill — and who it helps",
        snippet: "A breakdown of the major provisions: a 10-year path to citizenship for DACA recipients, expanded H-1B caps, and $12 billion for border infrastructure.",
        url: "https://nytimes.com",
        publishedAt: "2024-11-12T17:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-004-4",
        outlet: "Politico",
        outletDomain: "politico.com",
        headline: "Inside the Senate deal: who got what in the immigration compromise",
        snippet: "Politico reveals the closed-door negotiations, concessions made to moderate Republicans, and the political calculus behind the rare bipartisan agreement.",
        url: "https://politico.com",
        publishedAt: "2024-11-12T20:00:00Z",
        tone: "neutral",
      },
    ],
    tags: ["immigration", "senate", "bipartisan", "politics"],
  },
  {
    id: "story-005",
    title: "Pharmaceutical Giant Announces Phase 3 Results for Alzheimer's Drug",
    summary:
      "A major pharmaceutical company reported positive Phase 3 trial results for a new Alzheimer's treatment, showing a significant slowdown in cognitive decline in early-stage patients.",
    category: "health",
    imageUrl:
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80",
    publishedRange: { from: "2024-11-11T07:00:00Z", to: "2024-11-11T19:00:00Z" },
    sources: [
      {
        id: "src-005-1",
        outlet: "STAT News",
        outletDomain: "statnews.com",
        headline: "Alzheimer's drug shows promise but safety questions linger",
        snippet: "While the trial met its primary endpoint, a significant subset of patients experienced brain swelling and microbleeds, raising questions about the risk-benefit profile.",
        url: "https://statnews.com",
        publishedAt: "2024-11-11T07:00:00Z",
        tone: "mixed",
      },
      {
        id: "src-005-2",
        outlet: "NBC News",
        outletDomain: "nbcnews.com",
        headline: "'A real breakthrough': Alzheimer's drug slows memory loss in trial",
        snippet: "Patients and families celebrated the news, with doctors calling the results a meaningful step forward in treating one of the most devastating diseases.",
        url: "https://nbcnews.com",
        publishedAt: "2024-11-11T10:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-005-3",
        outlet: "Reuters Health",
        outletDomain: "reuters.com",
        headline: "Drug maker shares surge after Alzheimer's trial data released",
        snippet: "Shares in the pharmaceutical company rose 18% after the company reported the Phase 3 results, as analysts raised price targets ahead of an expected FDA submission.",
        url: "https://reuters.com",
        publishedAt: "2024-11-11T13:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["alzheimers", "pharma", "clinical trial", "health"],
  },
  {
    id: "story-006",
    title: "SpaceX Starship Completes First Successful Ocean Landing",
    summary:
      "SpaceX's Starship rocket completed its first fully successful integrated flight test, with both the Super Heavy booster and the upper stage vehicle returning safely.",
    category: "science",
    imageUrl:
      "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?w=800&q=80",
    publishedRange: { from: "2024-11-10T16:00:00Z", to: "2024-11-10T22:00:00Z" },
    sources: [
      {
        id: "src-006-1",
        outlet: "Ars Technica",
        outletDomain: "arstechnica.com",
        headline: "Starship sticks the landing: a technical deep-dive",
        snippet: "Ars Technica breaks down the engineering milestones — the chopstick catch attempt, the Raptor engine performance, and what it all means for Starship's path to orbit.",
        url: "https://arstechnica.com",
        publishedAt: "2024-11-10T16:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-006-2",
        outlet: "BBC Science",
        outletDomain: "bbc.com",
        headline: "SpaceX Starship lands safely — why it matters for Moon and Mars missions",
        snippet: "The BBC explains the significance of SpaceX's latest achievement for NASA's Artemis moon program and Elon Musk's long-term vision of Mars colonization.",
        url: "https://bbc.com",
        publishedAt: "2024-11-10T18:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-006-3",
        outlet: "Scientific American",
        outletDomain: "scientificamerican.com",
        headline: "What scientists are cautiously optimistic about after Starship's flight",
        snippet: "Aerospace engineers and scientists offer measured praise for the landing while noting the long road still ahead before Starship becomes a reliable launch platform.",
        url: "https://scientificamerican.com",
        publishedAt: "2024-11-10T20:00:00Z",
        tone: "mixed",
      },
    ],
    tags: ["SpaceX", "Starship", "space", "NASA"],
  },
  // --- NEW STORIES ---
  {
    id: "story-007",
    title: "Supreme Court Hears Landmark Case on Social Media and Free Speech",
    summary:
      "The Supreme Court heard oral arguments in a pivotal case that could reshape the legal relationship between the First Amendment and social media content moderation.",
    category: "politics",
    imageUrl:
      "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    publishedRange: { from: "2024-11-09T09:00:00Z", to: "2024-11-09T21:00:00Z" },
    sources: [
      {
        id: "src-007-1",
        outlet: "SCOTUSblog",
        outletDomain: "scotusblog.com",
        headline: "Justices skeptical of state laws compelling social media speech",
        snippet: "Several justices signaled concerns that Texas and Florida laws requiring platforms to carry all speech could violate the First Amendment rights of the companies themselves.",
        url: "https://scotusblog.com",
        publishedAt: "2024-11-09T09:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-007-2",
        outlet: "Fox News",
        outletDomain: "foxnews.com",
        headline: "SCOTUS case could end Big Tech censorship of conservatives",
        snippet: "Conservative advocates argued before the nation's highest court that social media companies have systematically silenced right-leaning voices under the guise of content moderation.",
        url: "https://foxnews.com",
        publishedAt: "2024-11-09T11:00:00Z",
        tone: "critical",
      },
      {
        id: "src-007-3",
        outlet: "The Atlantic",
        outletDomain: "theatlantic.com",
        headline: "The Supreme Court case that could break the internet",
        snippet: "If states can dictate what content platforms must carry, the resulting chaos could fundamentally alter how online speech works — for everyone.",
        url: "https://theatlantic.com",
        publishedAt: "2024-11-09T14:00:00Z",
        tone: "critical",
      },
      {
        id: "src-007-4",
        outlet: "Washington Post",
        outletDomain: "washingtonpost.com",
        headline: "Supreme Court wrestles with social media's power to shape public discourse",
        snippet: "The justices struggled to find workable limits on state authority over platforms, with many asking pointed questions about hypothetical scenarios involving small businesses and political speech.",
        url: "https://washingtonpost.com",
        publishedAt: "2024-11-09T17:00:00Z",
        tone: "neutral",
      },
    ],
    tags: ["supreme court", "free speech", "social media", "first amendment"],
  },
  {
    id: "story-008",
    title: "Global Chip Shortage Eases as New Semiconductor Fabs Come Online",
    summary:
      "After three years of supply disruptions, new TSMC and Samsung fabs in the US and Europe are beginning to ease the global semiconductor shortage that hit automakers and electronics firms hardest.",
    category: "technology",
    imageUrl:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
    publishedRange: { from: "2024-11-08T08:00:00Z", to: "2024-11-08T20:00:00Z" },
    sources: [
      {
        id: "src-008-1",
        outlet: "Bloomberg Technology",
        outletDomain: "bloomberg.com",
        headline: "TSMC Arizona fab hits full production — what it means for chip supply",
        snippet: "The $40 billion Arizona facility is producing 3nm chips at scale, a milestone that analysts say will meaningfully reduce US dependence on Taiwan for advanced semiconductors.",
        url: "https://bloomberg.com",
        publishedAt: "2024-11-08T08:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-008-2",
        outlet: "The Economist",
        outletDomain: "economist.com",
        headline: "The chip shortage is ending, but at enormous cost to taxpayers",
        snippet: "Governments have committed over $200 billion in subsidies to semiconductor manufacturing. The question is whether this industrial policy will pay off — or merely shift geopolitical risk.",
        url: "https://economist.com",
        publishedAt: "2024-11-08T10:30:00Z",
        tone: "mixed",
      },
      {
        id: "src-008-3",
        outlet: "Reuters",
        outletDomain: "reuters.com",
        headline: "Auto industry cautiously optimistic as chip deliveries improve",
        snippet: "Carmakers including Ford and Volkswagen say lead times for microcontrollers have shortened significantly in Q3, allowing them to ramp up production of previously constrained models.",
        url: "https://reuters.com",
        publishedAt: "2024-11-08T13:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["semiconductors", "chips", "TSMC", "supply chain"],
  },
  {
    id: "story-009",
    title: "WHO Declares New Mpox Strain a Global Health Emergency",
    summary:
      "The World Health Organization issued its highest alert level for a new, more transmissible strain of mpox spreading across Central and East Africa, calling for coordinated international response.",
    category: "health",
    imageUrl:
      "https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=800&q=80",
    publishedRange: { from: "2024-11-07T06:00:00Z", to: "2024-11-07T22:00:00Z" },
    sources: [
      {
        id: "src-009-1",
        outlet: "Reuters Health",
        outletDomain: "reuters.com",
        headline: "WHO declares mpox emergency over new strain spreading in Africa",
        snippet: "The WHO Director-General invoked the highest level of international health alert, saying the new clade Ib variant requires immediate coordinated action from member states.",
        url: "https://reuters.com",
        publishedAt: "2024-11-07T06:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-009-2",
        outlet: "CNN Health",
        outletDomain: "cnn.com",
        headline: "Should you be worried about the new mpox strain? What experts say",
        snippet: "Health officials are urging calm while stressing the need for vaccine equity, as the new variant appears to spread more easily through household contact than its predecessor.",
        url: "https://cnn.com",
        publishedAt: "2024-11-07T10:00:00Z",
        tone: "mixed",
      },
      {
        id: "src-009-3",
        outlet: "The Guardian",
        outletDomain: "theguardian.com",
        headline: "Mpox emergency exposes vaccine inequality as rich nations hold stockpiles",
        snippet: "While wealthy countries have mpox vaccines in reserve, the African nations facing the outbreak have received only a fraction of the doses needed, highlighting global health inequity.",
        url: "https://theguardian.com",
        publishedAt: "2024-11-07T14:00:00Z",
        tone: "critical",
      },
      {
        id: "src-009-4",
        outlet: "STAT News",
        outletDomain: "statnews.com",
        headline: "What we know — and don't know — about mpox clade Ib",
        snippet: "Scientists are racing to characterize the new variant's transmissibility, severity, and vaccine effectiveness. Current data suggests existing vaccines still offer meaningful protection.",
        url: "https://statnews.com",
        publishedAt: "2024-11-07T18:00:00Z",
        tone: "neutral",
      },
    ],
    tags: ["mpox", "WHO", "health emergency", "Africa"],
  },
  {
    id: "story-010",
    title: "Major Banks Report Record Profits as Interest Income Surges",
    summary:
      "JPMorgan, Bank of America, and Goldman Sachs posted record quarterly profits, driven by elevated interest rates boosting lending income even as investment banking revenue lagged.",
    category: "business",
    imageUrl:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
    publishedRange: { from: "2024-11-06T08:00:00Z", to: "2024-11-06T18:00:00Z" },
    sources: [
      {
        id: "src-010-1",
        outlet: "Financial Times",
        outletDomain: "ft.com",
        headline: "Wall Street banks post record earnings as rate windfall continues",
        snippet: "The big six US banks collectively earned more than $40 billion in the quarter, with net interest income — the spread between borrowing and lending rates — accounting for the bulk of gains.",
        url: "https://ft.com",
        publishedAt: "2024-11-06T08:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-010-2",
        outlet: "New York Times",
        outletDomain: "nytimes.com",
        headline: "Banks are thriving. Americans carrying debt are not.",
        snippet: "Record bank profits come as credit card delinquencies hit a 12-year high, painting a picture of a two-speed economy where financial institutions profit from the same rates squeezing consumers.",
        url: "https://nytimes.com",
        publishedAt: "2024-11-06T11:00:00Z",
        tone: "critical",
      },
      {
        id: "src-010-3",
        outlet: "CNBC",
        outletDomain: "cnbc.com",
        headline: "JPMorgan smashes earnings estimates, raises full-year outlook",
        snippet: "CEO Jamie Dimon cautioned about geopolitical risks while delivering results that exceeded analyst forecasts by a wide margin, sending the stock to a new all-time high.",
        url: "https://cnbc.com",
        publishedAt: "2024-11-06T14:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["banking", "JPMorgan", "earnings", "economy"],
  },
  {
    id: "story-011",
    title: "Scientists Discover Potential Cure for Most Common Form of Blindness",
    summary:
      "Researchers at the University of Oxford announced early-stage clinical results for a gene therapy targeting age-related macular degeneration, the leading cause of blindness in adults over 50.",
    category: "science",
    imageUrl:
      "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80",
    publishedRange: { from: "2024-11-05T07:00:00Z", to: "2024-11-05T19:00:00Z" },
    sources: [
      {
        id: "src-011-1",
        outlet: "BBC Science",
        outletDomain: "bbc.com",
        headline: "Gene therapy restores sight in age-related blindness patients",
        snippet: "All 10 patients in the early trial showed measurable improvements in visual acuity three months after a single injection, with no serious adverse events reported.",
        url: "https://bbc.com",
        publishedAt: "2024-11-05T07:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-011-2",
        outlet: "STAT News",
        outletDomain: "statnews.com",
        headline: "Promising AMD gene therapy — but temper the excitement",
        snippet: "Phase 1 trials are designed to test safety, not efficacy. The Oxford results are genuinely exciting but experts caution years of larger trials lie ahead before this reaches patients.",
        url: "https://statnews.com",
        publishedAt: "2024-11-05T10:00:00Z",
        tone: "mixed",
      },
      {
        id: "src-011-3",
        outlet: "The Guardian",
        outletDomain: "theguardian.com",
        headline: "'I can see my grandchildren's faces': patients on gene therapy trial",
        snippet: "Personal accounts from trial participants give a human dimension to the clinical data, with several describing emotional reunions with family members they could previously not clearly see.",
        url: "https://theguardian.com",
        publishedAt: "2024-11-05T14:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["gene therapy", "blindness", "AMD", "Oxford"],
  },
  {
    id: "story-012",
    title: "Ukraine War Enters Third Year: Frontlines Shift as Western Aid Wavers",
    summary:
      "As the conflict enters its third year, Ukrainian forces are holding defensive lines amid fresh Russian offensives, while debates over continued Western military aid intensify in Washington and Brussels.",
    category: "world",
    imageUrl:
      "https://images.unsplash.com/photo-1646625978965-a70f97875a42?w=800&q=80",
    publishedRange: { from: "2024-11-04T06:00:00Z", to: "2024-11-04T22:00:00Z" },
    sources: [
      {
        id: "src-012-1",
        outlet: "Associated Press",
        outletDomain: "apnews.com",
        headline: "Ukraine holds key city as Russia presses renewed offensive in the east",
        snippet: "Ukrainian commanders report intense fighting around Pokrovsk, describing Russian advances as significant but saying defensive lines remain intact after 72 hours of sustained pressure.",
        url: "https://apnews.com",
        publishedAt: "2024-11-04T06:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-012-2",
        outlet: "RT",
        outletDomain: "rt.com",
        headline: "Russian forces liberate new villages in Donetsk, Ministry of Defence says",
        snippet: "Russia's defence ministry claimed advances across multiple fronts, stating that strategic high ground near Avdiivka had been secured by Russian forces.",
        url: "https://rt.com",
        publishedAt: "2024-11-04T08:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-012-3",
        outlet: "The Economist",
        outletDomain: "economist.com",
        headline: "Ukraine is not losing — but it needs more than hope",
        snippet: "The Economist's analysis finds Ukraine's military situation is difficult but not dire, provided Western partners maintain ammunition supplies and air defence systems through 2025.",
        url: "https://economist.com",
        publishedAt: "2024-11-04T12:00:00Z",
        tone: "mixed",
      },
      {
        id: "src-012-4",
        outlet: "Fox News",
        outletDomain: "foxnews.com",
        headline: "Republican hawks and doves clash over Ukraine aid as war drags on",
        snippet: "A growing faction of House Republicans is conditioning future aid on stricter oversight and an exit strategy, creating uncertainty for Kyiv as it plans its 2025 campaign.",
        url: "https://foxnews.com",
        publishedAt: "2024-11-04T17:00:00Z",
        tone: "mixed",
      },
    ],
    tags: ["Ukraine", "Russia", "war", "NATO"],
  },
  {
    id: "story-013",
    title: "Apple Vision Pro Sales Disappoint as Developers Abandon Platform",
    summary:
      "Reports emerged that Apple's spatial computing headset is underperforming sales targets by a wide margin, with several major app developers quietly shelving Vision Pro projects.",
    category: "technology",
    imageUrl:
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80",
    publishedRange: { from: "2024-11-03T08:00:00Z", to: "2024-11-03T20:00:00Z" },
    sources: [
      {
        id: "src-013-1",
        outlet: "Bloomberg",
        outletDomain: "bloomberg.com",
        headline: "Apple Vision Pro sales well below internal targets, sources say",
        snippet: "Apple has sold fewer than 500,000 Vision Pro units since launch — a fraction of the 1 million units per quarter the company had privately projected, according to people familiar with the matter.",
        url: "https://bloomberg.com",
        publishedAt: "2024-11-03T08:00:00Z",
        tone: "critical",
      },
      {
        id: "src-013-2",
        outlet: "The Verge",
        outletDomain: "theverge.com",
        headline: "The apps are leaving Vision Pro — here's why that matters",
        snippet: "Major developers including Netflix, YouTube, and Spotify have pulled or never launched Vision Pro apps. Without a compelling app ecosystem, the headset risks a slow death.",
        url: "https://theverge.com",
        publishedAt: "2024-11-03T10:30:00Z",
        tone: "critical",
      },
      {
        id: "src-013-3",
        outlet: "9to5Mac",
        outletDomain: "9to5mac.com",
        headline: "Apple Vision Pro is a first-gen product — judge it like one",
        snippet: "Apple's history is full of products that looked like failures before becoming dominant platforms. Dismissing Vision Pro after one year ignores the long arc of Apple's platform plays.",
        url: "https://9to5mac.com",
        publishedAt: "2024-11-03T14:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["Apple", "Vision Pro", "AR", "VR", "spatial computing"],
  },
  {
    id: "story-014",
    title: "G20 Nations Agree on Minimum Global Corporate Tax Framework",
    summary:
      "G20 leaders endorsed a framework to implement a 15% global minimum corporate tax, a landmark in international tax policy aimed at ending the race to the bottom on corporate rates.",
    category: "business",
    imageUrl:
      "https://images.unsplash.com/photo-1444653614773-995cb1ef9efa?w=800&q=80",
    publishedRange: { from: "2024-11-02T10:00:00Z", to: "2024-11-02T22:00:00Z" },
    sources: [
      {
        id: "src-014-1",
        outlet: "Financial Times",
        outletDomain: "ft.com",
        headline: "G20 backs global minimum tax in historic deal",
        snippet: "The agreement, backed by 136 countries representing 90% of global GDP, is the most significant reform to international corporate taxation in a century.",
        url: "https://ft.com",
        publishedAt: "2024-11-02T10:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-014-2",
        outlet: "Wall Street Journal",
        outletDomain: "wsj.com",
        headline: "Global minimum tax deal full of loopholes, critics warn",
        snippet: "Tax experts say carve-outs for substance-based income exclusions, transitional safe harbours, and bilateral treaty overrides could allow multinationals to continue paying well below 15%.",
        url: "https://wsj.com",
        publishedAt: "2024-11-02T13:00:00Z",
        tone: "critical",
      },
      {
        id: "src-014-3",
        outlet: "BBC Business",
        outletDomain: "bbc.com",
        headline: "What the global minimum tax means for your country",
        snippet: "The BBC breaks down winners and losers: small open economies like Ireland and Singapore face the biggest adjustments, while larger economies with big domestic markets stand to gain.",
        url: "https://bbc.com",
        publishedAt: "2024-11-02T16:00:00Z",
        tone: "neutral",
      },
    ],
    tags: ["G20", "corporate tax", "OECD", "global economy"],
  },
  {
    id: "story-015",
    title: "NBA Season Opens Amid Player Load Management Controversy",
    summary:
      "The NBA season tipped off with renewed debate over star players sitting out games for rest, as the league's new rules aimed at curbing load management face their first real test.",
    category: "sports",
    imageUrl:
      "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80",
    publishedRange: { from: "2024-11-01T15:00:00Z", to: "2024-11-01T23:00:00Z" },
    sources: [
      {
        id: "src-015-1",
        outlet: "ESPN",
        outletDomain: "espn.com",
        headline: "NBA's new load management rules put to first test on opening night",
        snippet: "Three marquee players sat out opening night games despite being listed as healthy, raising immediate questions about whether the league's new fines and penalties will change team behavior.",
        url: "https://espn.com",
        publishedAt: "2024-11-01T15:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-015-2",
        outlet: "The Athletic",
        outletDomain: "theathletic.com",
        headline: "Load management is a medical decision, not a PR problem",
        snippet: "Sports medicine experts argue the league's push to force stars to play risks long-term player health and career longevity, and that fans' short-term interests shouldn't override player welfare.",
        url: "https://theathletic.com",
        publishedAt: "2024-11-01T17:30:00Z",
        tone: "critical",
      },
      {
        id: "src-015-3",
        outlet: "New York Post",
        outletDomain: "nypost.com",
        headline: "Fans paid $400 a ticket to watch bench players — the NBA must act",
        snippet: "The Post's sports desk argues that fans deserve to see the stars they paid to watch, and that the league's toothless enforcement is a betrayal of the paying customer.",
        url: "https://nypost.com",
        publishedAt: "2024-11-01T20:00:00Z",
        tone: "critical",
      },
    ],
    tags: ["NBA", "basketball", "load management", "sports"],
  },
  {
    id: "story-016",
    title: "Hollywood Writers Strike Ends with New AI Protections in Contract",
    summary:
      "The Writers Guild of America reached a deal with the major studios, securing minimum staffing requirements, streaming residuals, and the industry's first-ever contractual protections against AI replacing writers.",
    category: "entertainment",
    imageUrl:
      "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80",
    publishedRange: { from: "2024-10-31T10:00:00Z", to: "2024-10-31T22:00:00Z" },
    sources: [
      {
        id: "src-016-1",
        outlet: "Variety",
        outletDomain: "variety.com",
        headline: "WGA deal: everything writers won — and what they gave up",
        snippet: "A detailed breakdown of the contract gains: minimum room staffing, improved streaming formulas, and AI provisions that prohibit studios from using AI to write or rewrite scripts without writer consent.",
        url: "https://variety.com",
        publishedAt: "2024-10-31T10:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-016-2",
        outlet: "The Hollywood Reporter",
        outletDomain: "hollywoodreporter.com",
        headline: "Studios celebrated after WGA deal — here's why they won too",
        snippet: "While writers secured meaningful gains, the studios preserved flexibility on mini-rooms, avoided the most expensive residual formulas, and kept AI provisions narrower than the WGA initially sought.",
        url: "https://hollywoodreporter.com",
        publishedAt: "2024-10-31T13:00:00Z",
        tone: "mixed",
      },
      {
        id: "src-016-3",
        outlet: "Wired",
        outletDomain: "wired.com",
        headline: "The WGA's AI deal is a template — every industry should be watching",
        snippet: "The clause barring AI from writing or rewriting scripts is the first major labor contract to directly restrict AI substitution of human workers. Other unions are already taking notes.",
        url: "https://wired.com",
        publishedAt: "2024-10-31T16:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["WGA", "Hollywood", "AI", "writers strike", "entertainment"],
  },
];

export const MOCK_ANALYSIS: Record<string, AIAnalysis> = {
  "story-001": {
    agree: [
      "The Federal Reserve held interest rates unchanged at this meeting",
      "The decision was unanimous among FOMC members",
      "Chair Jerome Powell cited the need for more economic data before making changes",
    ],
    differ: [
      {
        outlet: "Fox Business",
        angle: "Frames the decision negatively as a 'freeze,' emphasizing continued inflation risk and a stern warning tone from Powell",
      },
      {
        outlet: "Bloomberg",
        angle: "Focuses on the dovish undercurrent and positive market reaction, suggesting future cuts are on the horizon",
      },
      {
        outlet: "NPR",
        angle: "Centers the story on impact to ordinary consumers — mortgage rates, car loans, credit cards — rather than market or macro framing",
      },
    ],
    missingContext: [
      "The specific language changes in the FOMC statement that markets interpreted as dovish are not quoted in most outlets",
      "Historical comparison: how does this rate-hold streak compare to previous Fed cycles?",
      "Dissenting voices within the Fed who may have preferred a cut are not mentioned",
      "International central bank actions (ECB, Bank of England) that provide broader context are absent",
    ],
    generatedAt: new Date().toISOString(),
  },
};
