import type { Story, AIAnalysis } from "@/types";

export const MOCK_STORIES: Story[] = [
  {
    id: "story-001",
    title: "Federal Reserve Holds Interest Rates Steady Amid Economic Uncertainty",
    summary:
      "The Federal Reserve announced it would maintain current interest rates, citing mixed economic signals including persistent inflation and a cooling job market.",
    category: "business",
    region: "world" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    publishedRange: { from: "2024-11-15T10:00:00Z", to: "2024-11-15T18:30:00Z" },
    sources: [
      {
        id: "src-001-1",
        outlet: "Reuters",
        outletDomain: "reuters.com",
        headline: "Fed holds rates, signals cautious path ahead",
        snippet: "The Federal Reserve kept its benchmark interest rate unchanged Wednesday, with Chair Jerome Powell emphasizing that policymakers need more data before considering cuts.",
        url: "https://reuters.com",
        publishedAt: "2024-11-15T10:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-001-2",
        outlet: "Fox Business",
        outletDomain: "foxbusiness.com",
        headline: "Fed freezes rates again â€” inflation fight not over, Powell warns",
        snippet: "The Federal Reserve once again refused to cut interest rates, with Jerome Powell warning that inflation remains too high and the central bank will not rush to ease policy.",
        url: "https://foxbusiness.com",
        publishedAt: "2024-11-15T11:15:00Z",
        tone: "critical",
      },
      {
        id: "src-001-3",
        outlet: "Bloomberg",
        outletDomain: "bloomberg.com",
        headline: "Fed pauses rate cycle, markets rally on dovish commentary",
        snippet: "Federal Reserve officials voted unanimously to hold rates steady, while market participants focused on hints of future easing embedded in the post-meeting statement.",
        url: "https://bloomberg.com",
        publishedAt: "2024-11-15T12:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-001-4",
        outlet: "NPR",
        outletDomain: "npr.org",
        headline: "What the Fed's rate decision means for everyday Americans",
        snippet: "The Federal Reserve held interest rates steady for the third consecutive meeting, a decision that will keep borrowing costs elevated for mortgages, car loans, and credit cards.",
        url: "https://npr.org",
        publishedAt: "2024-11-15T14:00:00Z",
        tone: "neutral",
      },
    ],
    tags: ["federal reserve", "interest rates", "economy", "inflation"],
  },
  {
    id: "story-002",
    title: "Major AI Lab Releases Multimodal Model Claiming Human-Level Reasoning",
    summary:
      "A leading artificial intelligence company unveiled a new model it claims surpasses human performance on several benchmark reasoning tasks, reigniting debates about AGI timelines.",
    category: "technology",
    region: "world" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80",
    publishedRange: { from: "2024-11-14T09:00:00Z", to: "2024-11-14T22:00:00Z" },
    sources: [
      {
        id: "src-002-1",
        outlet: "The Verge",
        outletDomain: "theverge.com",
        headline: "New AI model claims human-level reasoning â€” researchers are skeptical",
        snippet: "The company's announcement was met with excitement from investors and skepticism from independent AI researchers who questioned the methodology behind the benchmark scores.",
        url: "https://theverge.com",
        publishedAt: "2024-11-14T09:00:00Z",
        tone: "mixed",
      },
      {
        id: "src-002-2",
        outlet: "Wired",
        outletDomain: "wired.com",
        headline: "The AI reasoning revolution is here â€” or is it?",
        snippet: "Wired examines what human-level reasoning actually means and why benchmark performance may not translate to real-world intelligence.",
        url: "https://wired.com",
        publishedAt: "2024-11-14T11:30:00Z",
        tone: "critical",
      },
      {
        id: "src-002-3",
        outlet: "TechCrunch",
        outletDomain: "techcrunch.com",
        headline: "AI startup raises $2B on the back of breakthrough reasoning model",
        snippet: "The announcement coincided with a massive funding round, raising questions about whether the timing was driven by scientific progress or investor relations.",
        url: "https://techcrunch.com",
        publishedAt: "2024-11-14T15:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-002-4",
        outlet: "BBC Technology",
        outletDomain: "bbc.com",
        headline: "AI that thinks like humans: what does it really mean?",
        snippet: "The BBC explores the philosophical and practical implications of a machine that can reportedly reason at or above the level of a typical adult human.",
        url: "https://bbc.com",
        publishedAt: "2024-11-14T18:00:00Z",
        tone: "neutral",
      },
    ],
    tags: ["artificial intelligence", "AI", "machine learning", "AGI"],
  },
  {
    id: "story-003",
    title: "Climate Summit Ends with Landmark Fossil Fuel Agreement",
    summary:
      "Delegates from 190 countries reached a historic accord committing to phase out fossil fuels over the next two decades, though critics argue the timeline is insufficient.",
    category: "world",
    region: "world" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&q=80",
    publishedRange: { from: "2024-11-13T08:00:00Z", to: "2024-11-13T20:00:00Z" },
    sources: [
      {
        id: "src-003-1",
        outlet: "The Guardian",
        outletDomain: "theguardian.com",
        headline: "Climate deal 'too little, too late' say scientists as summit wraps",
        snippet: "Environmental scientists and activist groups expressed disappointment with the 20-year phase-out timeline, arguing it falls far short of what is needed to limit warming to 1.5Â°C.",
        url: "https://theguardian.com",
        publishedAt: "2024-11-13T10:00:00Z",
        tone: "critical",
      },
      {
        id: "src-003-2",
        outlet: "Associated Press",
        outletDomain: "apnews.com",
        headline: "Nations agree to phase out fossil fuels in historic UN climate deal",
        snippet: "In a breakthrough moment at the COP climate conference, world leaders committed to a binding timeline to transition away from coal, oil, and gas over the next two decades.",
        url: "https://apnews.com",
        publishedAt: "2024-11-13T12:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-003-3",
        outlet: "Wall Street Journal",
        outletDomain: "wsj.com",
        headline: "Climate pact threatens energy security, industry groups warn",
        snippet: "Business and energy industry organizations cautioned that a rushed fossil fuel phase-out could trigger supply disruptions and economic instability in energy-dependent nations.",
        url: "https://wsj.com",
        publishedAt: "2024-11-13T14:30:00Z",
        tone: "critical",
      },
      {
        id: "src-003-4",
        outlet: "CNN",
        outletDomain: "cnn.com",
        headline: "World leaders hail 'historic' fossil fuel deal at climate summit",
        snippet: "World leaders from the US, EU, and major emerging economies praised the agreement, calling it the most significant climate commitment since the Paris Accord.",
        url: "https://cnn.com",
        publishedAt: "2024-11-13T16:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["climate change", "COP", "fossil fuels", "environment"],
  },
  {
    id: "story-004",
    title: "Senate Passes Sweeping Immigration Reform Bill",
    summary:
      "The Senate approved a bipartisan immigration reform package that includes a path to citizenship for undocumented immigrants and increased border security funding.",
    category: "politics",
    region: "lk" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&q=80",
    publishedRange: { from: "2024-11-12T14:00:00Z", to: "2024-11-12T23:00:00Z" },
    sources: [
      {
        id: "src-004-1",
        outlet: "CNN Politics",
        outletDomain: "cnn.com",
        headline: "Senate passes landmark immigration bill in rare bipartisan vote",
        snippet: "The legislation, which passed 64-36, represents the most significant overhaul of U.S. immigration law in nearly four decades.",
        url: "https://cnn.com",
        publishedAt: "2024-11-12T14:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-004-2",
        outlet: "Fox News",
        outletDomain: "foxnews.com",
        headline: "Senate immigration bill slammed as 'amnesty' by conservatives",
        snippet: "Critics on the right blasted the Senate-passed immigration legislation as a massive expansion of legal status for illegal aliens that will incentivize more border crossings.",
        url: "https://foxnews.com",
        publishedAt: "2024-11-12T15:30:00Z",
        tone: "critical",
      },
      {
        id: "src-004-3",
        outlet: "New York Times",
        outletDomain: "nytimes.com",
        headline: "What's in the Senate immigration bill â€” and who it helps",
        snippet: "A breakdown of the major provisions: a 10-year path to citizenship for DACA recipients, expanded H-1B caps, and $12 billion for border infrastructure.",
        url: "https://nytimes.com",
        publishedAt: "2024-11-12T17:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-004-4",
        outlet: "Politico",
        outletDomain: "politico.com",
        headline: "Inside the Senate deal: who got what in the immigration compromise",
        snippet: "Politico reveals the closed-door negotiations, concessions made to moderate Republicans, and the political calculus behind the rare bipartisan agreement.",
        url: "https://politico.com",
        publishedAt: "2024-11-12T20:00:00Z",
        tone: "neutral",
      },
    ],
    tags: ["immigration", "senate", "bipartisan", "politics"],
  },
  {
    id: "story-005",
    title: "Pharmaceutical Giant Announces Phase 3 Results for Alzheimer's Drug",
    summary:
      "A major pharmaceutical company reported positive Phase 3 trial results for a new Alzheimer's treatment, showing a significant slowdown in cognitive decline in early-stage patients.",
    category: "health",
    region: "world" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80",
    publishedRange: { from: "2024-11-11T07:00:00Z", to: "2024-11-11T19:00:00Z" },
    sources: [
      {
        id: "src-005-1",
        outlet: "STAT News",
        outletDomain: "statnews.com",
        headline: "Alzheimer's drug shows promise but safety questions linger",
        snippet: "While the trial met its primary endpoint, a significant subset of patients experienced brain swelling and microbleeds, raising questions about the risk-benefit profile.",
        url: "https://statnews.com",
        publishedAt: "2024-11-11T07:00:00Z",
        tone: "mixed",
      },
      {
        id: "src-005-2",
        outlet: "NBC News",
        outletDomain: "nbcnews.com",
        headline: "'A real breakthrough': Alzheimer's drug slows memory loss in trial",
        snippet: "Patients and families celebrated the news, with doctors calling the results a meaningful step forward in treating one of the most devastating diseases.",
        url: "https://nbcnews.com",
        publishedAt: "2024-11-11T10:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-005-3",
        outlet: "Reuters Health",
        outletDomain: "reuters.com",
        headline: "Drug maker shares surge after Alzheimer's trial data released",
        snippet: "Shares in the pharmaceutical company rose 18% after the company reported the Phase 3 results, as analysts raised price targets ahead of an expected FDA submission.",
        url: "https://reuters.com",
        publishedAt: "2024-11-11T13:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["alzheimers", "pharma", "clinical trial", "health"],
  },
  {
    id: "story-006",
    title: "SpaceX Starship Completes First Successful Ocean Landing",
    summary:
      "SpaceX's Starship rocket completed its first fully successful integrated flight test, with both the Super Heavy booster and the upper stage vehicle returning safely.",
    category: "science",
    region: "world" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?w=800&q=80",
    publishedRange: { from: "2024-11-10T16:00:00Z", to: "2024-11-10T22:00:00Z" },
    sources: [
      {
        id: "src-006-1",
        outlet: "Ars Technica",
        outletDomain: "arstechnica.com",
        headline: "Starship sticks the landing: a technical deep-dive",
        snippet: "Ars Technica breaks down the engineering milestones â€” the chopstick catch attempt, the Raptor engine performance, and what it all means for Starship's path to orbit.",
        url: "https://arstechnica.com",
        publishedAt: "2024-11-10T16:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-006-2",
        outlet: "BBC Science",
        outletDomain: "bbc.com",
        headline: "SpaceX Starship lands safely â€” why it matters for Moon and Mars missions",
        snippet: "The BBC explains the significance of SpaceX's latest achievement for NASA's Artemis moon program and Elon Musk's long-term vision of Mars colonization.",
        url: "https://bbc.com",
        publishedAt: "2024-11-10T18:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-006-3",
        outlet: "Scientific American",
        outletDomain: "scientificamerican.com",
        headline: "What scientists are cautiously optimistic about after Starship's flight",
        snippet: "Aerospace engineers and scientists offer measured praise for the landing while noting the long road still ahead before Starship becomes a reliable launch platform.",
        url: "https://scientificamerican.com",
        publishedAt: "2024-11-10T20:00:00Z",
        tone: "mixed",
      },
    ],
    tags: ["SpaceX", "Starship", "space", "NASA"],
  },
  // --- NEW STORIES ---
  {
    id: "story-007",
    title: "Supreme Court Hears Landmark Case on Social Media and Free Speech",
    summary:
      "The Supreme Court heard oral arguments in a pivotal case that could reshape the legal relationship between the First Amendment and social media content moderation.",
    category: "politics",
    region: "lk" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    publishedRange: { from: "2024-11-09T09:00:00Z", to: "2024-11-09T21:00:00Z" },
    sources: [
      {
        id: "src-007-1",
        outlet: "SCOTUSblog",
        outletDomain: "scotusblog.com",
        headline: "Justices skeptical of state laws compelling social media speech",
        snippet: "Several justices signaled concerns that Texas and Florida laws requiring platforms to carry all speech could violate the First Amendment rights of the companies themselves.",
        url: "https://scotusblog.com",
        publishedAt: "2024-11-09T09:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-007-2",
        outlet: "Fox News",
        outletDomain: "foxnews.com",
        headline: "SCOTUS case could end Big Tech censorship of conservatives",
        snippet: "Conservative advocates argued before the nation's highest court that social media companies have systematically silenced right-leaning voices under the guise of content moderation.",
        url: "https://foxnews.com",
        publishedAt: "2024-11-09T11:00:00Z",
        tone: "critical",
      },
      {
        id: "src-007-3",
        outlet: "The Atlantic",
        outletDomain: "theatlantic.com",
        headline: "The Supreme Court case that could break the internet",
        snippet: "If states can dictate what content platforms must carry, the resulting chaos could fundamentally alter how online speech works â€” for everyone.",
        url: "https://theatlantic.com",
        publishedAt: "2024-11-09T14:00:00Z",
        tone: "critical",
      },
      {
        id: "src-007-4",
        outlet: "Washington Post",
        outletDomain: "washingtonpost.com",
        headline: "Supreme Court wrestles with social media's power to shape public discourse",
        snippet: "The justices struggled to find workable limits on state authority over platforms, with many asking pointed questions about hypothetical scenarios involving small businesses and political speech.",
        url: "https://washingtonpost.com",
        publishedAt: "2024-11-09T17:00:00Z",
        tone: "neutral",
      },
    ],
    tags: ["supreme court", "free speech", "social media", "first amendment"],
  },
  {
    id: "story-008",
    title: "Global Chip Shortage Eases as New Semiconductor Fabs Come Online",
    summary:
      "After three years of supply disruptions, new TSMC and Samsung fabs in the US and Europe are beginning to ease the global semiconductor shortage that hit automakers and electronics firms hardest.",
    category: "technology",
    region: "world" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
    publishedRange: { from: "2024-11-08T08:00:00Z", to: "2024-11-08T20:00:00Z" },
    sources: [
      {
        id: "src-008-1",
        outlet: "Bloomberg Technology",
        outletDomain: "bloomberg.com",
        headline: "TSMC Arizona fab hits full production â€” what it means for chip supply",
        snippet: "The $40 billion Arizona facility is producing 3nm chips at scale, a milestone that analysts say will meaningfully reduce US dependence on Taiwan for advanced semiconductors.",
        url: "https://bloomberg.com",
        publishedAt: "2024-11-08T08:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-008-2",
        outlet: "The Economist",
        outletDomain: "economist.com",
        headline: "The chip shortage is ending, but at enormous cost to taxpayers",
        snippet: "Governments have committed over $200 billion in subsidies to semiconductor manufacturing. The question is whether this industrial policy will pay off â€” or merely shift geopolitical risk.",
        url: "https://economist.com",
        publishedAt: "2024-11-08T10:30:00Z",
        tone: "mixed",
      },
      {
        id: "src-008-3",
        outlet: "Reuters",
        outletDomain: "reuters.com",
        headline: "Auto industry cautiously optimistic as chip deliveries improve",
        snippet: "Carmakers including Ford and Volkswagen say lead times for microcontrollers have shortened significantly in Q3, allowing them to ramp up production of previously constrained models.",
        url: "https://reuters.com",
        publishedAt: "2024-11-08T13:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["semiconductors", "chips", "TSMC", "supply chain"],
  },
  {
    id: "story-009",
    title: "WHO Declares New Mpox Strain a Global Health Emergency",
    summary:
      "The World Health Organization issued its highest alert level for a new, more transmissible strain of mpox spreading across Central and East Africa, calling for coordinated international response.",
    category: "health",
    region: "world" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=800&q=80",
    publishedRange: { from: "2024-11-07T06:00:00Z", to: "2024-11-07T22:00:00Z" },
    sources: [
      {
        id: "src-009-1",
        outlet: "Reuters Health",
        outletDomain: "reuters.com",
        headline: "WHO declares mpox emergency over new strain spreading in Africa",
        snippet: "The WHO Director-General invoked the highest level of international health alert, saying the new clade Ib variant requires immediate coordinated action from member states.",
        url: "https://reuters.com",
        publishedAt: "2024-11-07T06:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-009-2",
        outlet: "CNN Health",
        outletDomain: "cnn.com",
        headline: "Should you be worried about the new mpox strain? What experts say",
        snippet: "Health officials are urging calm while stressing the need for vaccine equity, as the new variant appears to spread more easily through household contact than its predecessor.",
        url: "https://cnn.com",
        publishedAt: "2024-11-07T10:00:00Z",
        tone: "mixed",
      },
      {
        id: "src-009-3",
        outlet: "The Guardian",
        outletDomain: "theguardian.com",
        headline: "Mpox emergency exposes vaccine inequality as rich nations hold stockpiles",
        snippet: "While wealthy countries have mpox vaccines in reserve, the African nations facing the outbreak have received only a fraction of the doses needed, highlighting global health inequity.",
        url: "https://theguardian.com",
        publishedAt: "2024-11-07T14:00:00Z",
        tone: "critical",
      },
      {
        id: "src-009-4",
        outlet: "STAT News",
        outletDomain: "statnews.com",
        headline: "What we know â€” and don't know â€” about mpox clade Ib",
        snippet: "Scientists are racing to characterize the new variant's transmissibility, severity, and vaccine effectiveness. Current data suggests existing vaccines still offer meaningful protection.",
        url: "https://statnews.com",
        publishedAt: "2024-11-07T18:00:00Z",
        tone: "neutral",
      },
    ],
    tags: ["mpox", "WHO", "health emergency", "Africa"],
  },
  {
    id: "story-010",
    title: "Major Banks Report Record Profits as Interest Income Surges",
    summary:
      "JPMorgan, Bank of America, and Goldman Sachs posted record quarterly profits, driven by elevated interest rates boosting lending income even as investment banking revenue lagged.",
    category: "business",
    region: "world" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
    publishedRange: { from: "2024-11-06T08:00:00Z", to: "2024-11-06T18:00:00Z" },
    sources: [
      {
        id: "src-010-1",
        outlet: "Financial Times",
        outletDomain: "ft.com",
        headline: "Wall Street banks post record earnings as rate windfall continues",
        snippet: "The big six US banks collectively earned more than $40 billion in the quarter, with net interest income â€” the spread between borrowing and lending rates â€” accounting for the bulk of gains.",
        url: "https://ft.com",
        publishedAt: "2024-11-06T08:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-010-2",
        outlet: "New York Times",
        outletDomain: "nytimes.com",
        headline: "Banks are thriving. Americans carrying debt are not.",
        snippet: "Record bank profits come as credit card delinquencies hit a 12-year high, painting a picture of a two-speed economy where financial institutions profit from the same rates squeezing consumers.",
        url: "https://nytimes.com",
        publishedAt: "2024-11-06T11:00:00Z",
        tone: "critical",
      },
      {
        id: "src-010-3",
        outlet: "CNBC",
        outletDomain: "cnbc.com",
        headline: "JPMorgan smashes earnings estimates, raises full-year outlook",
        snippet: "CEO Jamie Dimon cautioned about geopolitical risks while delivering results that exceeded analyst forecasts by a wide margin, sending the stock to a new all-time high.",
        url: "https://cnbc.com",
        publishedAt: "2024-11-06T14:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["banking", "JPMorgan", "earnings", "economy"],
  },
  {
    id: "story-011",
    title: "Scientists Discover Potential Cure for Most Common Form of Blindness",
    summary:
      "Researchers at the University of Oxford announced early-stage clinical results for a gene therapy targeting age-related macular degeneration, the leading cause of blindness in adults over 50.",
    category: "science",
    region: "world" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80",
    publishedRange: { from: "2024-11-05T07:00:00Z", to: "2024-11-05T19:00:00Z" },
    sources: [
      {
        id: "src-011-1",
        outlet: "BBC Science",
        outletDomain: "bbc.com",
        headline: "Gene therapy restores sight in age-related blindness patients",
        snippet: "All 10 patients in the early trial showed measurable improvements in visual acuity three months after a single injection, with no serious adverse events reported.",
        url: "https://bbc.com",
        publishedAt: "2024-11-05T07:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-011-2",
        outlet: "STAT News",
        outletDomain: "statnews.com",
        headline: "Promising AMD gene therapy â€” but temper the excitement",
        snippet: "Phase 1 trials are designed to test safety, not efficacy. The Oxford results are genuinely exciting but experts caution years of larger trials lie ahead before this reaches patients.",
        url: "https://statnews.com",
        publishedAt: "2024-11-05T10:00:00Z",
        tone: "mixed",
      },
      {
        id: "src-011-3",
        outlet: "The Guardian",
        outletDomain: "theguardian.com",
        headline: "'I can see my grandchildren's faces': patients on gene therapy trial",
        snippet: "Personal accounts from trial participants give a human dimension to the clinical data, with several describing emotional reunions with family members they could previously not clearly see.",
        url: "https://theguardian.com",
        publishedAt: "2024-11-05T14:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["gene therapy", "blindness", "AMD", "Oxford"],
  },
  {
    id: "story-012",
    title: "Ukraine War Enters Third Year: Frontlines Shift as Western Aid Wavers",
    summary:
      "As the conflict enters its third year, Ukrainian forces are holding defensive lines amid fresh Russian offensives, while debates over continued Western military aid intensify in Washington and Brussels.",
    category: "world",
    region: "world" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1646625978965-a70f97875a42?w=800&q=80",
    publishedRange: { from: "2024-11-04T06:00:00Z", to: "2024-11-04T22:00:00Z" },
    sources: [
      {
        id: "src-012-1",
        outlet: "Associated Press",
        outletDomain: "apnews.com",
        headline: "Ukraine holds key city as Russia presses renewed offensive in the east",
        snippet: "Ukrainian commanders report intense fighting around Pokrovsk, describing Russian advances as significant but saying defensive lines remain intact after 72 hours of sustained pressure.",
        url: "https://apnews.com",
        publishedAt: "2024-11-04T06:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-012-2",
        outlet: "RT",
        outletDomain: "rt.com",
        headline: "Russian forces liberate new villages in Donetsk, Ministry of Defence says",
        snippet: "Russia's defence ministry claimed advances across multiple fronts, stating that strategic high ground near Avdiivka had been secured by Russian forces.",
        url: "https://rt.com",
        publishedAt: "2024-11-04T08:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-012-3",
        outlet: "The Economist",
        outletDomain: "economist.com",
        headline: "Ukraine is not losing â€” but it needs more than hope",
        snippet: "The Economist's analysis finds Ukraine's military situation is difficult but not dire, provided Western partners maintain ammunition supplies and air defence systems through 2025.",
        url: "https://economist.com",
        publishedAt: "2024-11-04T12:00:00Z",
        tone: "mixed",
      },
      {
        id: "src-012-4",
        outlet: "Fox News",
        outletDomain: "foxnews.com",
        headline: "Republican hawks and doves clash over Ukraine aid as war drags on",
        snippet: "A growing faction of House Republicans is conditioning future aid on stricter oversight and an exit strategy, creating uncertainty for Kyiv as it plans its 2025 campaign.",
        url: "https://foxnews.com",
        publishedAt: "2024-11-04T17:00:00Z",
        tone: "mixed",
      },
    ],
    tags: ["Ukraine", "Russia", "war", "NATO"],
  },
  {
    id: "story-013",
    title: "Apple Vision Pro Sales Disappoint as Developers Abandon Platform",
    summary:
      "Reports emerged that Apple's spatial computing headset is underperforming sales targets by a wide margin, with several major app developers quietly shelving Vision Pro projects.",
    category: "technology",
    region: "world" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80",
    publishedRange: { from: "2024-11-03T08:00:00Z", to: "2024-11-03T20:00:00Z" },
    sources: [
      {
        id: "src-013-1",
        outlet: "Bloomberg",
        outletDomain: "bloomberg.com",
        headline: "Apple Vision Pro sales well below internal targets, sources say",
        snippet: "Apple has sold fewer than 500,000 Vision Pro units since launch â€” a fraction of the 1 million units per quarter the company had privately projected, according to people familiar with the matter.",
        url: "https://bloomberg.com",
        publishedAt: "2024-11-03T08:00:00Z",
        tone: "critical",
      },
      {
        id: "src-013-2",
        outlet: "The Verge",
        outletDomain: "theverge.com",
        headline: "The apps are leaving Vision Pro â€” here's why that matters",
        snippet: "Major developers including Netflix, YouTube, and Spotify have pulled or never launched Vision Pro apps. Without a compelling app ecosystem, the headset risks a slow death.",
        url: "https://theverge.com",
        publishedAt: "2024-11-03T10:30:00Z",
        tone: "critical",
      },
      {
        id: "src-013-3",
        outlet: "9to5Mac",
        outletDomain: "9to5mac.com",
        headline: "Apple Vision Pro is a first-gen product â€” judge it like one",
        snippet: "Apple's history is full of products that looked like failures before becoming dominant platforms. Dismissing Vision Pro after one year ignores the long arc of Apple's platform plays.",
        url: "https://9to5mac.com",
        publishedAt: "2024-11-03T14:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["Apple", "Vision Pro", "AR", "VR", "spatial computing"],
  },
  {
    id: "story-014",
    title: "G20 Nations Agree on Minimum Global Corporate Tax Framework",
    summary:
      "G20 leaders endorsed a framework to implement a 15% global minimum corporate tax, a landmark in international tax policy aimed at ending the race to the bottom on corporate rates.",
    category: "business",
    region: "world" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1444653614773-995cb1ef9efa?w=800&q=80",
    publishedRange: { from: "2024-11-02T10:00:00Z", to: "2024-11-02T22:00:00Z" },
    sources: [
      {
        id: "src-014-1",
        outlet: "Financial Times",
        outletDomain: "ft.com",
        headline: "G20 backs global minimum tax in historic deal",
        snippet: "The agreement, backed by 136 countries representing 90% of global GDP, is the most significant reform to international corporate taxation in a century.",
        url: "https://ft.com",
        publishedAt: "2024-11-02T10:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-014-2",
        outlet: "Wall Street Journal",
        outletDomain: "wsj.com",
        headline: "Global minimum tax deal full of loopholes, critics warn",
        snippet: "Tax experts say carve-outs for substance-based income exclusions, transitional safe harbours, and bilateral treaty overrides could allow multinationals to continue paying well below 15%.",
        url: "https://wsj.com",
        publishedAt: "2024-11-02T13:00:00Z",
        tone: "critical",
      },
      {
        id: "src-014-3",
        outlet: "BBC Business",
        outletDomain: "bbc.com",
        headline: "What the global minimum tax means for your country",
        snippet: "The BBC breaks down winners and losers: small open economies like Ireland and Singapore face the biggest adjustments, while larger economies with big domestic markets stand to gain.",
        url: "https://bbc.com",
        publishedAt: "2024-11-02T16:00:00Z",
        tone: "neutral",
      },
    ],
    tags: ["G20", "corporate tax", "OECD", "global economy"],
  },
  {
    id: "story-015",
    title: "NBA Season Opens Amid Player Load Management Controversy",
    summary:
      "The NBA season tipped off with renewed debate over star players sitting out games for rest, as the league's new rules aimed at curbing load management face their first real test.",
    category: "sports",
    region: "lk" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80",
    publishedRange: { from: "2024-11-01T15:00:00Z", to: "2024-11-01T23:00:00Z" },
    sources: [
      {
        id: "src-015-1",
        outlet: "ESPN",
        outletDomain: "espn.com",
        headline: "NBA's new load management rules put to first test on opening night",
        snippet: "Three marquee players sat out opening night games despite being listed as healthy, raising immediate questions about whether the league's new fines and penalties will change team behavior.",
        url: "https://espn.com",
        publishedAt: "2024-11-01T15:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-015-2",
        outlet: "The Athletic",
        outletDomain: "theathletic.com",
        headline: "Load management is a medical decision, not a PR problem",
        snippet: "Sports medicine experts argue the league's push to force stars to play risks long-term player health and career longevity, and that fans' short-term interests shouldn't override player welfare.",
        url: "https://theathletic.com",
        publishedAt: "2024-11-01T17:30:00Z",
        tone: "critical",
      },
      {
        id: "src-015-3",
        outlet: "New York Post",
        outletDomain: "nypost.com",
        headline: "Fans paid $400 a ticket to watch bench players â€” the NBA must act",
        snippet: "The Post's sports desk argues that fans deserve to see the stars they paid to watch, and that the league's toothless enforcement is a betrayal of the paying customer.",
        url: "https://nypost.com",
        publishedAt: "2024-11-01T20:00:00Z",
        tone: "critical",
      },
    ],
    tags: ["NBA", "basketball", "load management", "sports"],
  },
  {
    id: "story-016",
    title: "Hollywood Writers Strike Ends with New AI Protections in Contract",
    summary:
      "The Writers Guild of America reached a deal with the major studios, securing minimum staffing requirements, streaming residuals, and the industry's first-ever contractual protections against AI replacing writers.",
    category: "entertainment",
    region: "world" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80",
    publishedRange: { from: "2024-10-31T10:00:00Z", to: "2024-10-31T22:00:00Z" },
    sources: [
      {
        id: "src-016-1",
        outlet: "Variety",
        outletDomain: "variety.com",
        headline: "WGA deal: everything writers won â€” and what they gave up",
        snippet: "A detailed breakdown of the contract gains: minimum room staffing, improved streaming formulas, and AI provisions that prohibit studios from using AI to write or rewrite scripts without writer consent.",
        url: "https://variety.com",
        publishedAt: "2024-10-31T10:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-016-2",
        outlet: "The Hollywood Reporter",
        outletDomain: "hollywoodreporter.com",
        headline: "Studios celebrated after WGA deal â€” here's why they won too",
        snippet: "While writers secured meaningful gains, the studios preserved flexibility on mini-rooms, avoided the most expensive residual formulas, and kept AI provisions narrower than the WGA initially sought.",
        url: "https://hollywoodreporter.com",
        publishedAt: "2024-10-31T13:00:00Z",
        tone: "mixed",
      },
      {
        id: "src-016-3",
        outlet: "Wired",
        outletDomain: "wired.com",
        headline: "The WGA's AI deal is a template â€” every industry should be watching",
        snippet: "The clause barring AI from writing or rewriting scripts is the first major labor contract to directly restrict AI substitution of human workers. Other unions are already taking notes.",
        url: "https://wired.com",
        publishedAt: "2024-10-31T16:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["WGA", "Hollywood", "AI", "writers strike", "entertainment"],
  },

  // --- SRI LANKA POLITICS ---
  {
    id: "story-lk-p-001",
    title: "Sri Lanka Parliament Passes Landmark Anti-Corruption Bill",
    summary:
      "The Sri Lankan Parliament approved sweeping anti-corruption legislation aimed at strengthening the powers of the Commission to Investigate Allegations of Bribery or Corruption (CIABOC), amid IMF reform pressure.",
    category: "politics",
    region: "lk" as const,
    isBreaking: true,
    imageUrl:
      "https://images.unsplash.com/photo-1555848962-6e79363ec58f?w=800&q=80",
    publishedRange: { from: "2024-11-16T08:00:00Z", to: "2024-11-16T18:00:00Z" },
    sources: [
      {
        id: "src-lkp1-1",
        outlet: "Daily Mirror Sri Lanka",
        outletDomain: "dailymirror.lk",
        headline: "Parliament passes Anti-Corruption Act with bipartisan support",
        snippet:
          "MPs from both the ruling NPP and opposition parties backed the bill, described as a critical step toward meeting IMF governance benchmarks tied to the country's $2.9 billion bailout program.",
        url: "https://dailymirror.lk",
        publishedAt: "2024-11-16T08:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-lkp1-2",
        outlet: "Colombo Gazette",
        outletDomain: "colombogazette.com",
        headline: "Anti-corruption bill passes — but activists say it lacks teeth",
        snippet:
          "Civil society organisations expressed cautious welcome but noted that the bill's whistleblower protection clauses were significantly watered down during the committee stage.",
        url: "https://colombogazette.com",
        publishedAt: "2024-11-16T10:30:00Z",
        tone: "mixed",
      },
      {
        id: "src-lkp1-3",
        outlet: "The Island",
        outletDomain: "island.lk",
        headline: "SL parliament signals reform intent with CIABOC overhaul",
        snippet:
          "The Island's parliamentary correspondent analyses how the new act restructures CIABOC's independence, prosecution powers, and asset disclosure requirements for public officials.",
        url: "https://island.lk",
        publishedAt: "2024-11-16T12:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-lkp1-4",
        outlet: "BBC Sinhala",
        outletDomain: "bbc.com",
        headline: "Sri Lanka anti-graft law: what it means for ordinary citizens",
        snippet:
          "BBC Sinhala breaks down the legislation's real-world impact — from how citizens can report corruption to what penalties officials now face.",
        url: "https://bbc.com",
        publishedAt: "2024-11-16T15:00:00Z",
        tone: "neutral",
      },
    ],
    tags: ["sri lanka", "parliament", "anti-corruption", "IMF", "politics"],
  },
  {
    id: "story-lk-p-002",
    title: "President Dissanayake Announces Cabinet Reshuffle Amid Economic Recovery Push",
    summary:
      "Sri Lankan President Anura Kumara Dissanayake reshuffled the cabinet, appointing new ministers to key economic portfolios as the government accelerates its post-crisis recovery strategy under the IMF program.",
    category: "politics",
    region: "lk" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&q=80",
    publishedRange: { from: "2024-11-14T09:00:00Z", to: "2024-11-14T20:00:00Z" },
    sources: [
      {
        id: "src-lkp2-1",
        outlet: "Colombo Gazette",
        outletDomain: "colombogazette.com",
        headline: "President reshuffles cabinet, focuses on economic revival",
        snippet:
          "Key changes include a new Finance Minister with a private sector background and a restructured Ministry of Tourism, signalling the government's pivot to revenue generation.",
        url: "https://colombogazette.com",
        publishedAt: "2024-11-14T09:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-lkp2-2",
        outlet: "Ceylon Today",
        outletDomain: "ceylontoday.lk",
        headline: "Opposition slams reshuffle as 'musical chairs without substance'",
        snippet:
          "Opposition leader Sajith Premadasa criticised the cabinet changes, arguing the same NPP inner circle remains in charge and no genuine expertise has been brought in.",
        url: "https://ceylontoday.lk",
        publishedAt: "2024-11-14T12:00:00Z",
        tone: "critical",
      },
      {
        id: "src-lkp2-3",
        outlet: "Reuters",
        outletDomain: "reuters.com",
        headline: "Sri Lanka cabinet change aims to accelerate IMF reforms",
        snippet:
          "International analysts say the reshuffle reflects pressure from the IMF and bilateral creditors to demonstrate governance reforms ahead of the fourth programme review.",
        url: "https://reuters.com",
        publishedAt: "2024-11-14T16:00:00Z",
        tone: "neutral",
      },
    ],
    tags: ["sri lanka", "cabinet", "Dissanayake", "IMF", "economy"],
  },
  {
    id: "story-lk-p-003",
    title: "Sri Lanka's IMF Bailout Fourth Review: What's at Stake",
    summary:
      "With Sri Lanka's fourth IMF programme review approaching, analysts assess the country's progress on fiscal targets, debt restructuring, and structural reforms required to unlock the next tranche.",
    category: "politics",
    region: "lk" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    publishedRange: { from: "2024-11-12T07:00:00Z", to: "2024-11-12T19:00:00Z" },
    sources: [
      {
        id: "src-lkp3-1",
        outlet: "The Island",
        outletDomain: "island.lk",
        headline: "Fourth IMF review: targets met on paper, doubts remain on delivery",
        snippet:
          "Economists warn that while headline fiscal numbers may satisfy IMF criteria, structural reforms in state-owned enterprises and tax administration are lagging.",
        url: "https://island.lk",
        publishedAt: "2024-11-12T07:00:00Z",
        tone: "mixed",
      },
      {
        id: "src-lkp3-2",
        outlet: "Daily FT",
        outletDomain: "ft.lk",
        headline: "Sri Lanka on track for IMF review, Treasury says",
        snippet:
          "The Finance Ministry issued a statement citing primary surplus targets and revenue collection figures as evidence of compliance with programme benchmarks.",
        url: "https://ft.lk",
        publishedAt: "2024-11-12T10:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-lkp3-3",
        outlet: "Financial Times",
        outletDomain: "ft.com",
        headline: "Sri Lanka's debt deal progress opens door for next IMF tranche",
        snippet:
          "Agreements with bilateral creditors Japan, India, and the Paris Club-aligned nations have cleared a key hurdle, though bondholder negotiations remain ongoing.",
        url: "https://ft.com",
        publishedAt: "2024-11-12T15:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["sri lanka", "IMF", "economy", "debt", "fiscal"],
  },

  // --- SRI LANKA SPORTS ---
  {
    id: "story-lk-s-001",
    title: "Sri Lanka Cricket Stuns Australia in ICC Champions Trophy Opener",
    summary:
      "Sri Lanka recorded a stunning 47-run upset victory over Australia in the ICC Champions Trophy opening match, with spinner Wanindu Hasaranga taking five wickets to skittle the defending champions.",
    category: "sports",
    region: "lk" as const,
    isBreaking: true,
    imageUrl:
      "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&q=80",
    publishedRange: { from: "2024-11-15T13:00:00Z", to: "2024-11-15T22:00:00Z" },
    sources: [
      {
        id: "src-lks1-1",
        outlet: "Daily Mirror Sri Lanka",
        outletDomain: "dailymirror.lk",
        headline: "Lanka lions roar! Hasaranga five-for sinks Australia",
        snippet:
          "A nation erupted in celebration as Sri Lanka's spinners dismantled Australia's batting lineup, sealing a remarkable victory that signals the team's resurgence under new coach Sanath Jayasuriya.",
        url: "https://dailymirror.lk",
        publishedAt: "2024-11-15T13:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-lks1-2",
        outlet: "ESPNcricinfo",
        outletDomain: "espncricinfo.com",
        headline: "Hasaranga masterclass leaves Australia stunned in Champions Trophy opener",
        snippet:
          "ESPNcricinfo's match report details how Hasaranga's variations and the pitch conditions combined to produce one of Sri Lanka cricket's finest recent victories.",
        url: "https://espncricinfo.com",
        publishedAt: "2024-11-15T15:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-lks1-3",
        outlet: "Sydney Morning Herald",
        outletDomain: "smh.com.au",
        headline: "Shock defeat exposes Australia's middle-order frailty",
        snippet:
          "Australia's top order collapsed against the turning ball, with the Herald's cricket reporter questioning the team's preparation for subcontinental conditions.",
        url: "https://smh.com.au",
        publishedAt: "2024-11-15T18:00:00Z",
        tone: "critical",
      },
      {
        id: "src-lks1-4",
        outlet: "BBC Sport",
        outletDomain: "bbc.com",
        headline: "Sri Lanka cricket's renaissance: Hasaranga leads the charge",
        snippet:
          "The BBC analyses how Sri Lanka has rebuilt since the 2022 economic crisis disrupted cricketing infrastructure, and what this result means for the team's tournament prospects.",
        url: "https://bbc.com",
        publishedAt: "2024-11-15T20:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["sri lanka", "cricket", "ICC", "Champions Trophy", "Hasaranga"],
  },
  {
    id: "story-lk-s-002",
    title: "Sri Lanka Rugby Team Qualifies for Asia Rugby Championship Final",
    summary:
      "The Sri Lanka national rugby union team secured a place in the Asia Rugby Championship Division I final with a commanding win over Hong Kong, marking their best performance in a decade.",
    category: "sports",
    region: "lk" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80",
    publishedRange: { from: "2024-11-13T10:00:00Z", to: "2024-11-13T18:00:00Z" },
    sources: [
      {
        id: "src-lks2-1",
        outlet: "Ceylon Today",
        outletDomain: "ceylontoday.lk",
        headline: "Rugby Tuskers storm into Asia Championship final",
        snippet:
          "Sri Lanka's national rugby team produced a disciplined 28-14 victory, with the forwards dominating the set piece and scrum-half Aslam Ibrahim controlling the tempo.",
        url: "https://ceylontoday.lk",
        publishedAt: "2024-11-13T10:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-lks2-2",
        outlet: "Asia Rugby",
        outletDomain: "asiarugby.com",
        headline: "Sri Lanka and Japan set for title showdown in Colombo",
        snippet:
          "Asia Rugby's official report confirms the final fixture details, noting that Sri Lanka's home advantage at Racecourse Grounds could prove decisive against a stronger Japan side.",
        url: "https://asiarugby.com",
        publishedAt: "2024-11-13T14:00:00Z",
        tone: "neutral",
      },
    ],
    tags: ["sri lanka", "rugby", "Asia Rugby Championship", "sports"],
  },
  {
    id: "story-lk-s-003",
    title: "Colombo Marathon Draws Record 15,000 Runners from 40 Countries",
    summary:
      "The annual Colombo International Marathon set a new participation record, with Ethiopian athlete Tigist Assefa setting a new course record and Sri Lankan runner Niluka Gimhana achieving a personal best.",
    category: "sports",
    region: "lk" as const,
    isBreaking: false,
    imageUrl:
      "https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=800&q=80",
    publishedRange: { from: "2024-11-10T05:00:00Z", to: "2024-11-10T14:00:00Z" },
    sources: [
      {
        id: "src-lks3-1",
        outlet: "Colombo Gazette",
        outletDomain: "colombogazette.com",
        headline: "Record crowd, record times at Colombo International Marathon",
        snippet:
          "The Galle Face seafront course drew its largest-ever field, with participants ranging from elite international runners to local fun runners, in an event the tourism ministry called a major showcase for Colombo.",
        url: "https://colombogazette.com",
        publishedAt: "2024-11-10T05:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-lks3-2",
        outlet: "Daily Mirror Sri Lanka",
        outletDomain: "dailymirror.lk",
        headline: "Gimhana's sub-2:20 puts him in contention for Asian Games selection",
        snippet:
          "Athletics Sri Lanka officials confirmed that Niluka Gimhana's performance meets the qualifying standard for the upcoming Asian Games, making him a likely pick for the national team.",
        url: "https://dailymirror.lk",
        publishedAt: "2024-11-10T10:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["sri lanka", "marathon", "Colombo", "athletics", "sports"],
  },

  // --- NEW SRI LANKA POLITICS (June 2025) ---
  {
    id: "story-lk-p-004",
    title: "President AKD Meets Indian PM Modi in New Delhi to Strengthen Bilateral Ties",
    summary:
      "President Anura Kumara Dissanayake held high-level talks with Indian Prime Minister Narendra Modi in New Delhi, focusing on debt relief, the Adani energy deal, and a proposed economic partnership corridor between the two nations.",
    category: "politics",
    region: "lk" as const,
    isBreaking: true,
    imageUrl: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&q=80",
    publishedRange: { from: "2025-06-18T06:00:00Z", to: "2025-06-18T20:00:00Z" },
    sources: [
      {
        id: "src-lkp4-1",
        outlet: "Daily Mirror Sri Lanka",
        outletDomain: "dailymirror.lk",
        headline: "AKD-Modi summit: India pledges continued support for Sri Lanka's recovery",
        snippet:
          "President Dissanayake's two-day state visit to India resulted in agreements covering renewable energy investment, fishermen's rights in the Palk Strait, and a concessional credit line for infrastructure projects.",
        url: "https://dailymirror.lk",
        publishedAt: "2025-06-18T06:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-lkp4-2",
        outlet: "The Island",
        outletDomain: "island.lk",
        headline: "Adani port deal back on table as AKD visits Modi",
        snippet:
          "The Island's diplomatic correspondent reports that the controversial Adani Group investment in Colombo port's West Container Terminal featured prominently in bilateral discussions, despite earlier domestic opposition.",
        url: "https://island.lk",
        publishedAt: "2025-06-18T09:00:00Z",
        tone: "mixed",
      },
      {
        id: "src-lkp4-3",
        outlet: "Reuters",
        outletDomain: "reuters.com",
        headline: "Sri Lanka and India ink energy, connectivity deals at summit",
        snippet:
          "The two countries signed four MoUs covering power grid interconnection, a digital payments corridor, fisheries cooperation, and a $300 million Indian credit facility for northern Sri Lanka infrastructure.",
        url: "https://reuters.com",
        publishedAt: "2025-06-18T12:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-lkp4-4",
        outlet: "Al Jazeera",
        outletDomain: "aljazeera.com",
        headline: "Can Sri Lanka balance India and China as it seeks economic recovery?",
        snippet:
          "Al Jazeera analyses Sri Lanka's diplomatic tightrope: deepening ties with India while maintaining Chinese investments in ports, roads, and the Hambantota zone.",
        url: "https://aljazeera.com",
        publishedAt: "2025-06-18T16:00:00Z",
        tone: "neutral",
      },
    ],
    tags: ["sri lanka", "india", "AKD", "Modi", "bilateral", "diplomacy"],
  },
  {
    id: "story-lk-p-005",
    title: "Sri Lanka Budget 2025: Tax Hikes, Public Sector Wage Freeze Spark Protests",
    summary:
      "The government's mid-year budget revision introduced VAT increases on essential goods and extended the public sector wage freeze, prompting trade union-led protests outside the Finance Ministry in Colombo.",
    category: "politics",
    region: "lk" as const,
    isBreaking: false,
    imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    publishedRange: { from: "2025-06-15T08:00:00Z", to: "2025-06-15T21:00:00Z" },
    sources: [
      {
        id: "src-lkp5-1",
        outlet: "Daily FT",
        outletDomain: "ft.lk",
        headline: "Mid-year budget revision raises VAT, extends wage freeze under IMF pressure",
        snippet:
          "Finance Minister Shehan Semasinghe defended the measures as unavoidable conditions of the IMF programme, arguing that fiscal discipline now will enable wage increases from 2026 onwards.",
        url: "https://ft.lk",
        publishedAt: "2025-06-15T08:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-lkp5-2",
        outlet: "Ceylon Today",
        outletDomain: "ceylontoday.lk",
        headline: "Unions call nationwide strike over wage freeze extension",
        snippet:
          "The Joint Trade Union Alliance announced a 48-hour strike across state banks, schools, and hospitals after parliament approved the budget revision without any relief for public sector workers.",
        url: "https://ceylontoday.lk",
        publishedAt: "2025-06-15T11:00:00Z",
        tone: "critical",
      },
      {
        id: "src-lkp5-3",
        outlet: "BBC Sinhala",
        outletDomain: "bbc.com",
        headline: "Sri Lanka budget squeeze: who bears the burden?",
        snippet:
          "BBC Sinhala surveys economists and ordinary citizens about the real-world impact of higher taxes on food and fuel, and the continued freeze on government salaries.",
        url: "https://bbc.com",
        publishedAt: "2025-06-15T15:00:00Z",
        tone: "mixed",
      },
    ],
    tags: ["sri lanka", "budget", "IMF", "VAT", "protests", "economy"],
  },
  {
    id: "story-lk-p-006",
    title: "SJB and NPP Clash Over Local Government Election Date",
    summary:
      "The main opposition Samagi Jana Balawegaya accused the ruling NPP government of unconstitutionally delaying local government elections, filing a petition in the Supreme Court demanding a date be set within 60 days.",
    category: "politics",
    region: "lk" as const,
    isBreaking: false,
    imageUrl: "https://images.unsplash.com/photo-1555848962-6e79363ec58f?w=800&q=80",
    publishedRange: { from: "2025-06-14T07:00:00Z", to: "2025-06-14T19:00:00Z" },
    sources: [
      {
        id: "src-lkp6-1",
        outlet: "Colombo Gazette",
        outletDomain: "colombogazette.com",
        headline: "SJB files SC petition demanding local polls within 60 days",
        snippet:
          "The petition argues that the Elections Commission's continued deferral of local government polls violates citizens' fundamental right to vote and undermines democratic accountability at the grassroots level.",
        url: "https://colombogazette.com",
        publishedAt: "2025-06-14T07:00:00Z",
        tone: "critical",
      },
      {
        id: "src-lkp6-2",
        outlet: "The Island",
        outletDomain: "island.lk",
        headline: "NPP defends election delay citing financial constraints, EC independence",
        snippet:
          "Government spokesman Nalinda Jayatissa said local elections would be held once the Elections Commission confirms readiness, dismissing the SJB petition as politically motivated.",
        url: "https://island.lk",
        publishedAt: "2025-06-14T11:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-lkp6-3",
        outlet: "Daily Mirror Sri Lanka",
        outletDomain: "dailymirror.lk",
        headline: "Supreme Court to hear election delay petition next week",
        snippet:
          "The Supreme Court granted leave to proceed and scheduled a hearing for June 23, marking the first major constitutional challenge to the NPP government since it took office.",
        url: "https://dailymirror.lk",
        publishedAt: "2025-06-14T15:00:00Z",
        tone: "neutral",
      },
    ],
    tags: ["sri lanka", "elections", "SJB", "NPP", "supreme court", "democracy"],
  },
  {
    id: "story-lk-p-007",
    title: "Sri Lanka Formally Exits IMF Watch List After Completing Debt Restructuring",
    summary:
      "The International Monetary Fund confirmed Sri Lanka has successfully completed its external debt restructuring process, removing the country from enhanced monitoring and unlocking the final tranche of its $2.9 billion bailout.",
    category: "politics",
    region: "lk" as const,
    isBreaking: true,
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
    publishedRange: { from: "2025-06-17T09:00:00Z", to: "2025-06-17T22:00:00Z" },
    sources: [
      {
        id: "src-lkp7-1",
        outlet: "Daily FT",
        outletDomain: "ft.lk",
        headline: "Sri Lanka exits IMF enhanced monitoring — a milestone in recovery",
        snippet:
          "The IMF's announcement marks the formal end of the most intensive phase of oversight, with the Fund citing significant progress on fiscal consolidation, state enterprise reform, and debt sustainability.",
        url: "https://ft.lk",
        publishedAt: "2025-06-17T09:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-lkp7-2",
        outlet: "Financial Times",
        outletDomain: "ft.com",
        headline: "Sri Lanka's debt deal: a model for other distressed economies?",
        snippet:
          "The FT analyses whether Sri Lanka's 'comparability of treatment' debt settlement with China, India, and Paris Club creditors can serve as a template for other developing nations facing insolvency.",
        url: "https://ft.com",
        publishedAt: "2025-06-17T13:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-lkp7-3",
        outlet: "Colombo Gazette",
        outletDomain: "colombogazette.com",
        headline: "Ordinary Sri Lankans ask: when will the recovery reach us?",
        snippet:
          "Despite the macro milestone, surveys show most Sri Lankan households still face higher living costs, reduced public services, and stagnant wages — raising questions about who benefits from the recovery.",
        url: "https://colombogazette.com",
        publishedAt: "2025-06-17T17:00:00Z",
        tone: "mixed",
      },
    ],
    tags: ["sri lanka", "IMF", "debt restructuring", "economy", "recovery"],
  },

  // --- NEW SRI LANKA SPORTS (June 2025) ---
  {
    id: "story-lk-s-004",
    title: "Sri Lanka vs Pakistan T20 Series: Lanka Win Series 3-1 at Home",
    summary:
      "Sri Lanka sealed a comprehensive T20 series victory over Pakistan, winning 3-1 at the R. Premadasa Stadium in Colombo, with Pathum Nissanka scoring two half-centuries and Maheesh Theekshana claiming seven wickets across the series.",
    category: "sports",
    region: "lk" as const,
    isBreaking: true,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&q=80",
    publishedRange: { from: "2025-06-19T14:00:00Z", to: "2025-06-19T23:00:00Z" },
    sources: [
      {
        id: "src-lks4-1",
        outlet: "ESPNcricinfo",
        outletDomain: "espncricinfo.com",
        headline: "Sri Lanka complete dominant T20 series win over Pakistan",
        snippet:
          "A mature batting display from Nissanka and smart death bowling by Theekshana sealed a 3-1 series result, with Sri Lanka captain Charith Asalanka hailing the performance as the team's best in two years.",
        url: "https://espncricinfo.com",
        publishedAt: "2025-06-19T14:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-lks4-2",
        outlet: "Daily Mirror Sri Lanka",
        outletDomain: "dailymirror.lk",
        headline: "Lanka T20 heroes — Nissanka and Theekshana shine in series win",
        snippet:
          "Sri Lanka's homegrown talent delivered when it mattered most, as a packed R. Premadasa gave the team a rousing send-off ahead of next month's Asia Cup.",
        url: "https://dailymirror.lk",
        publishedAt: "2025-06-19T16:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-lks4-3",
        outlet: "Dawn Pakistan",
        outletDomain: "dawn.com",
        headline: "Pakistan's T20 struggles deepen after Sri Lanka series defeat",
        snippet:
          "Pakistan's selectors face difficult questions after a fourth T20 series loss in Asia this year, with the batting middle order once again failing to anchor innings under pressure.",
        url: "https://dawn.com",
        publishedAt: "2025-06-19T19:00:00Z",
        tone: "critical",
      },
      {
        id: "src-lks4-4",
        outlet: "BBC Sport",
        outletDomain: "bbc.com",
        headline: "Sri Lanka's T20 revival: what's driving the resurgence?",
        snippet:
          "The BBC looks at the coaching changes, youth development pipeline, and tactical shifts that have transformed Sri Lanka into a formidable T20 side over the past 18 months.",
        url: "https://bbc.com",
        publishedAt: "2025-06-19T21:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["sri lanka", "cricket", "T20", "Pakistan", "Nissanka", "Theekshana"],
  },
  {
    id: "story-lk-s-005",
    title: "Dilshan Madushanka Named Sri Lanka's ICC Men's Cricketer of the Month",
    summary:
      "Left-arm pacer Dilshan Madushanka was awarded the ICC Men's Cricket of the Month award for June 2025 after a series of match-winning performances in both ODI and T20 formats.",
    category: "sports",
    region: "lk" as const,
    isBreaking: false,
    imageUrl: "https://images.unsplash.com/photo-1540747913346-19212a4b423f?w=800&q=80",
    publishedRange: { from: "2025-06-16T08:00:00Z", to: "2025-06-16T18:00:00Z" },
    sources: [
      {
        id: "src-lks5-1",
        outlet: "ICC",
        outletDomain: "icc-cricket.com",
        headline: "Madushanka wins ICC Men's Cricketer of the Month — June 2025",
        snippet:
          "The ICC cited Madushanka's 14 wickets across six matches in June, including two five-wicket hauls, as the decisive factor in his selection over nominees from India and Australia.",
        url: "https://icc-cricket.com",
        publishedAt: "2025-06-16T08:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-lks5-2",
        outlet: "Ceylon Today",
        outletDomain: "ceylontoday.lk",
        headline: "Pride of Lanka: Madushanka's ICC award is a national moment",
        snippet:
          "Reaction from Sri Lanka poured in on social media, with former cricketers Mahela Jayawardena and Kumar Sangakkara both congratulating the young pacer on the global recognition.",
        url: "https://ceylontoday.lk",
        publishedAt: "2025-06-16T11:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-lks5-3",
        outlet: "ESPNcricinfo",
        outletDomain: "espncricinfo.com",
        headline: "What makes Madushanka Sri Lanka's most dangerous bowler right now",
        snippet:
          "ESPNcricinfo's analysis examines Madushanka's yorker accuracy, pace variation, and ability to swing the ball late — skills that have made him one of the most effective death bowlers in world cricket.",
        url: "https://espncricinfo.com",
        publishedAt: "2025-06-16T15:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["sri lanka", "cricket", "Madushanka", "ICC", "award"],
  },
  {
    id: "story-lk-s-006",
    title: "Sri Lanka Wins Gold at South Asian Games — Athletics and Swimming Lead",
    summary:
      "Sri Lanka finished third on the medal table at the 2025 South Asian Games in Dhaka, with athletes claiming 12 gold medals — the country's best ever haul — led by sprinter Yupun Abeykoon and swimmer Matthew Abeysinghe.",
    category: "sports",
    region: "lk" as const,
    isBreaking: false,
    imageUrl: "https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=800&q=80",
    publishedRange: { from: "2025-06-13T06:00:00Z", to: "2025-06-13T20:00:00Z" },
    sources: [
      {
        id: "src-lks6-1",
        outlet: "Daily Mirror Sri Lanka",
        outletDomain: "dailymirror.lk",
        headline: "Historic gold rush! Sri Lanka's best-ever South Asian Games haul",
        snippet:
          "Twelve gold medals across athletics, swimming, boxing, and weightlifting put Sri Lanka third on the table behind India and Pakistan — a landmark result that Sports Minister Roshan Ranasinghe called 'a turning point for Sri Lankan sport'.",
        url: "https://dailymirror.lk",
        publishedAt: "2025-06-13T06:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-lks6-2",
        outlet: "Colombo Gazette",
        outletDomain: "colombogazette.com",
        headline: "Yupun Abeykoon sprint double puts Sri Lanka on the map",
        snippet:
          "Yupun Abeykoon claimed gold in both the 100m and 200m, with his 9.96 second 100m clocking described by coaches as a potential Asian record qualifier if ratified under World Athletics conditions.",
        url: "https://colombogazette.com",
        publishedAt: "2025-06-13T10:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-lks6-3",
        outlet: "South Asian Games Official",
        outletDomain: "southasiangames.org",
        headline: "2025 South Asian Games final medal table — India tops, Sri Lanka third",
        snippet:
          "The official Games report confirms Sri Lanka's 12 gold, 9 silver, 14 bronze final tally — a near-doubling of their previous best performance and a strong signal ahead of the 2026 Asian Games.",
        url: "https://southasiangames.org",
        publishedAt: "2025-06-13T16:00:00Z",
        tone: "neutral",
      },
    ],
    tags: ["sri lanka", "South Asian Games", "Abeykoon", "athletics", "Abeysinghe", "swimming"],
  },
  {
    id: "story-lk-s-007",
    title: "SL Football: National Team Qualifies for SAFF Championship Semifinals",
    summary:
      "Sri Lanka's national football team advanced to the semifinals of the SAFF Championship for the first time in eight years, beating Nepal 2-1 in Kathmandu in a tense group-stage decider.",
    category: "sports",
    region: "lk" as const,
    isBreaking: false,
    imageUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80",
    publishedRange: { from: "2025-06-12T15:00:00Z", to: "2025-06-12T22:00:00Z" },
    sources: [
      {
        id: "src-lks7-1",
        outlet: "Ceylon Today",
        outletDomain: "ceylontoday.lk",
        headline: "Lanka Lions roar into SAFF semis with dramatic Nepal win",
        snippet:
          "A 90th-minute winner from substitute Channa Ediri sent Sri Lanka into the SAFF Championship semifinals for the first time since 2017, sparking celebrations across the island.",
        url: "https://ceylontoday.lk",
        publishedAt: "2025-06-12T15:00:00Z",
        tone: "favorable",
      },
      {
        id: "src-lks7-2",
        outlet: "SAFF Official",
        outletDomain: "saff.com.bd",
        headline: "SAFF Championship semifinal lineup confirmed",
        snippet:
          "Sri Lanka will face India in one semifinal while Bangladesh take on Maldives in the other, with matches scheduled for June 16 at the Dashrath Stadium in Kathmandu.",
        url: "https://saff.com.bd",
        publishedAt: "2025-06-12T18:00:00Z",
        tone: "neutral",
      },
      {
        id: "src-lks7-3",
        outlet: "Colombo Gazette",
        outletDomain: "colombogazette.com",
        headline: "Football fans dare to dream: Sri Lanka in SAFF semis after 8 years",
        snippet:
          "Fans gathered at the Sugathadasa Stadium to watch the match on big screens erupted in scenes not seen since the 2008 tournament, with the national team's youth development programme finally bearing fruit.",
        url: "https://colombogazette.com",
        publishedAt: "2025-06-12T20:00:00Z",
        tone: "favorable",
      },
    ],
    tags: ["sri lanka", "football", "SAFF Championship", "Nepal", "soccer"],
  },
];

export const MOCK_ANALYSIS: Record<string, AIAnalysis> = {
  "story-001": {
    agree: [
      "The Federal Reserve held interest rates unchanged at this meeting",
      "The decision was unanimous among FOMC members",
      "Chair Jerome Powell cited the need for more economic data before making changes",
    ],
    differ: [
      {
        outlet: "Fox Business",
        angle: "Frames the decision negatively as a 'freeze,' emphasizing continued inflation risk and a stern warning tone from Powell",
      },
      {
        outlet: "Bloomberg",
        angle: "Focuses on the dovish undercurrent and positive market reaction, suggesting future cuts are on the horizon",
      },
      {
        outlet: "NPR",
        angle: "Centers the story on impact to ordinary consumers â€” mortgage rates, car loans, credit cards â€” rather than market or macro framing",
      },
    ],
    missingContext: [
      "The specific language changes in the FOMC statement that markets interpreted as dovish are not quoted in most outlets",
      "Historical comparison: how does this rate-hold streak compare to previous Fed cycles?",
      "Dissenting voices within the Fed who may have preferred a cut are not mentioned",
      "International central bank actions (ECB, Bank of England) that provide broader context are absent",
    ],
    generatedAt: new Date().toISOString(),
  },
};

