import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Sparkles, Globe2, ShieldAlert, RefreshCw } from "lucide-react";

export const metadata: Metadata = {
  title: "About Multiview",
  description:
    "Learn how Multiview selects sources, clusters stories, and uses AI to analyze coverage differences.",
};

export default function AboutPage() {
  return (
    <div className="bg-white">
      {/* Hero */}
      <div className="bg-primary text-white py-20">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <p className="text-blue-300 text-sm font-medium uppercase tracking-widest mb-4">
            About
          </p>
          <h1 className="text-4xl md:text-5xl font-bold leading-tight mb-6">
            Why we built Multiview
          </h1>
          <p className="text-blue-100 text-xl leading-relaxed max-w-2xl">
            The same event can look completely different depending on where you
            read about it. Multiview makes those differences visible — and uses AI
            to explain them.
          </p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 space-y-16">
        {/* Methodology */}
        <section id="methodology">
          <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-3">
            <Globe2 className="w-6 h-6 text-primary" />
            How source selection works
          </h2>
          <div className="prose prose-gray max-w-none space-y-4 text-gray-600 leading-relaxed">
            <p>
              Multiview pulls articles from the NewsAPI aggregation service, which
              indexes headlines from hundreds of English-language outlets including
              CNN, BBC, Reuters, Fox News, the Guardian, Bloomberg, AP News, NPR,
              Politico, and many more.
            </p>
            <p>
              For a given topic or category, we fetch the most recent articles and
              apply a lightweight clustering algorithm: articles whose headlines
              share a significant proportion of high-frequency keywords (words longer
              than 4 characters) within a recent time window are grouped together as
              covering the &ldquo;same story.&rdquo; This is a best-effort v1 approach — it will
              occasionally group loosely related coverage and may miss genuine duplicates
              with very different headlines.
            </p>
            <p>
              We normalize each article into a <code>SourceArticle</code> object with
              a tone estimate (neutral, favorable, critical, or mixed) derived from
              sentiment keywords in the headline and description. This is a heuristic
              — it is not a rigorous bias measurement.
            </p>
          </div>
        </section>

        {/* AI analysis */}
        <section id="ai-analysis">
          <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-3">
            <Sparkles className="w-6 h-6 text-[#5C4033]" />
            How AI analysis works
          </h2>
          <div className="space-y-4 text-gray-600 leading-relaxed">
            <p>
              The &ldquo;AI Highlights&rdquo; panel is generated by Claude (Anthropic) via the
              Anthropic API. When you open a story comparison page, the server sends
              all article headlines and snippets to Claude with a structured prompt
              asking it to identify:
            </p>
            <ul className="list-none space-y-3 pl-0">
              {[
                {
                  title: "Points of agreement",
                  desc: "Factual claims present across all or most sources.",
                },
                {
                  title: "Points of disagreement",
                  desc: "How specific outlets frame, emphasize, or contextualize the same facts differently.",
                },
                {
                  title: "Missing context",
                  desc: "Important background, data, or perspectives absent from the coverage.",
                },
              ].map((item) => (
                <li key={item.title} className="flex gap-3 items-start">
                  <div className="w-1.5 h-1.5 rounded-full bg-[#5C4033] mt-2.5 shrink-0" />
                  <div>
                    <span className="font-semibold text-gray-900">{item.title}: </span>
                    {item.desc}
                  </div>
                </li>
              ))}
            </ul>
            <p>
              The model is asked to return structured JSON. Analysis results are cached
              in memory for one hour to reduce redundant API calls.
            </p>
          </div>
        </section>

        {/* Disclaimer */}
        <section
          id="disclaimer"
          className="p-8 rounded-2xl border-2 border-[#5C4033]/20 bg-[#F5F0EB]"
        >
          <h2 className="text-xl font-bold text-[#5C4033] mb-5 flex items-center gap-3">
            <ShieldAlert className="w-5 h-5" />
            Important disclaimers
          </h2>
          <div className="space-y-3 text-sm text-[#5C4033]/80 leading-relaxed">
            <p>
              <strong className="text-[#5C4033]">AI analysis is not authoritative.</strong>{" "}
              Claude&apos;s summaries are generated from article snippets, not full text.
              They may be incomplete, miscategorized, or reflect the model&apos;s own
              framing. Always read the original articles.
            </p>
            <p>
              <strong className="text-[#5C4033]">Tone indicators are heuristics.</strong>{" "}
              The neutral/critical/favorable labels are based on simple keyword matching
              in headlines and descriptions. They are not peer-reviewed bias
              measurements.
            </p>
            <p>
              <strong className="text-[#5C4033]">Story clustering is approximate.</strong>{" "}
              The algorithm that groups articles into &ldquo;the same story&rdquo; is not perfect.
              Unrelated articles may occasionally be grouped together.
            </p>
            <p>
              <strong className="text-[#5C4033]">No affiliation.</strong>{" "}
              Multiview is not affiliated with any of the news outlets it indexes.
              Article content and links belong to their respective publishers.
            </p>
          </div>
        </section>

        {/* Provider swap note */}
        <section id="providers">
          <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-3">
            <RefreshCw className="w-6 h-6 text-primary" />
            Swapping the news provider
          </h2>
          <div className="space-y-4 text-gray-600 leading-relaxed">
            <p>
              Multiview uses an adapter pattern for news data. The current default
              is <strong>NewsAPI.org</strong>. To swap in GNews or Mediastack:
            </p>
            <ol className="list-decimal pl-5 space-y-2">
              <li>
                Implement the <code className="text-primary bg-primary-light px-1.5 py-0.5 rounded text-sm">NewsProvider</code> interface
                in <code className="text-sm bg-gray-100 px-1.5 py-0.5 rounded">src/lib/newsapi.ts</code>
              </li>
              <li>
                Update <code className="text-sm bg-gray-100 px-1.5 py-0.5 rounded">getNewsProvider()</code> to
                instantiate your new class
              </li>
              <li>
                Set the appropriate API key in <code className="text-sm bg-gray-100 px-1.5 py-0.5 rounded">.env.local</code>
              </li>
            </ol>
          </div>
        </section>

        <div className="text-center pt-4 border-t border-gray-100">
          <Link
            href="/"
            className="inline-flex items-center gap-2 px-6 py-3 bg-primary text-white font-bold rounded-xl hover:bg-primary-hover transition-colors"
          >
            Start exploring stories
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </div>
    </div>
  );
}
