import Link from "next/link";
import { CATEGORIES } from "@/types";

export default function Footer() {
  return (
    <footer className="bg-primary text-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-12">
          {/* Brand */}
          <div className="md:col-span-2">
            <div className="flex items-center gap-2 mb-4">
              <div className="w-8 h-8 bg-white rounded-sm flex items-center justify-center">
                <span className="text-primary font-bold text-sm">M</span>
              </div>
              <span className="font-bold text-xl tracking-tight">
                multi<span className="text-blue-300">view</span>
              </span>
            </div>
            <p className="text-blue-200 text-sm leading-relaxed max-w-sm">
              Multiview compares how different news outlets cover the same story,
              with AI-generated analysis of agreement, disagreement, and missing
              context. Understand the full picture.
            </p>
            <p className="mt-6 text-xs text-blue-300/70 leading-relaxed">
              AI analysis is generated by Claude (Anthropic) and should be treated
              as a starting point for critical reading, not a definitive account.
              Always read primary sources.
            </p>
          </div>

          {/* Categories */}
          <div>
            <h3 className="text-xs font-bold uppercase tracking-widest text-blue-300 mb-4">
              Categories
            </h3>
            <ul className="space-y-2">
              {CATEGORIES.map((cat) => (
                <li key={cat.slug}>
                  <Link
                    href={`/category/${cat.slug}`}
                    className="text-sm text-blue-200 hover:text-white transition-colors"
                  >
                    {cat.label}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          {/* Site */}
          <div>
            <h3 className="text-xs font-bold uppercase tracking-widest text-blue-300 mb-4">
              Site
            </h3>
            <ul className="space-y-2">
              {[
                { href: "/", label: "Home" },
                { href: "/about", label: "About" },
                { href: "/about#methodology", label: "Methodology" },
                { href: "/about#disclaimer", label: "AI Disclaimer" },
              ].map((item) => (
                <li key={item.href}>
                  <Link
                    href={item.href}
                    className="text-sm text-blue-200 hover:text-white transition-colors"
                  >
                    {item.label}
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="mt-12 pt-8 border-t border-primary-hover/40 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-xs text-blue-300/70">
            © {new Date().getFullYear()} Multiview. Built with Next.js & Anthropic Claude.
          </p>
          <p className="text-xs text-blue-300/70">
            News data provided by NewsAPI.org. Not affiliated with any outlet.
          </p>
        </div>
      </div>
    </footer>
  );
}
